"""
Build the Indus11 SRS document.

Structure and formatting follow the department template and the internal
guide's review comments:

  - 1.5 line spacing throughout — every paragraph, including table cells,
    captions and headings — and justified running text
  - 2.54 cm (1 in) margins on all four sides
  - no stray space before/after paragraphs
  - only chapters start on a new page; chapter titles centred at 16 pt,
    sub-topic titles at 14 pt
  - figures numbered per chapter (Figure 4.1, 5.3, ...), no repeated titles
  - every store is given its own data-dictionary table
  - Conclusion, References and Definitions appear last, unnumbered
  - References begin on their own page
  - the six UML/DFD figures (docs/diagrams/final-*.png) are supplied images —
    the dark-theme diagrams the user generated and asked to keep as-is, not
    PlantUML/Graphviz renders. They are not regenerated by this script; replace
    the PNG in place if a diagram needs to change. The .puml/.dot sources for
    the Times-New-Roman versions these replaced are left in the repo for
    reference but are no longer wired into the build.

    python docs/build_srs.py
"""
import json
import os

from docx import Document
from docx.enum.section import WD_SECTION
from docx.enum.table import WD_TABLE_ALIGNMENT
from docx.enum.text import WD_ALIGN_PARAGRAPH, WD_BREAK
from docx.oxml import OxmlElement
from docx.oxml.ns import qn
from docx.enum.text import WD_TAB_ALIGNMENT, WD_TAB_LEADER
from docx.shared import Inches, Pt, RGBColor
from PIL import Image, ImageFont

HERE = os.path.dirname(os.path.abspath(__file__))
DIAGRAMS = os.path.join(HERE, "diagrams")
SHOT = os.path.join(HERE, "screenshot-dashboard.png")
OUT = os.path.expanduser("~/Downloads/Indus11_SRS.docx")

with open(os.path.join(HERE, "eval-results.json")) as f:
    EVAL = json.load(f)
FLAGGED, GRAPH, COUNTS = EVAL["metrics"]["flagged"], EVAL["graph"], EVAL["counts"]

FONT = "Times New Roman"
BODY, SUB, CHAP = 12, 14, 16
LINE = 1.5                # every paragraph in the document, no exceptions
INK = RGBColor(0, 0, 0)
MARGIN = 1.0               # inches; 2.54 cm on all four sides
USABLE_W = 8.5 - 2 * MARGIN
MAX_FIG_H = 7.0

figures, tables = [], []   # (label, title) for the front-matter lists
# label -> (first cell of the first row, first cell of the last row). The PDF
# driver checks both land on one page, i.e. that no table straddles a break.
table_spans = {}
contents = []              # (level, title) for the table of contents

# Page numbers for the contents, produced by a first pass over the rendered PDF
# (docs/make_srs_pdf.py). Absent on the first pass, which is why the entries are
# laid out identically either way — the pagination must not shift between passes.
try:
    with open(os.path.join(HERE, "toc-pages.json")) as f:
        TOC_PAGES = json.load(f)
except FileNotFoundError:
    TOC_PAGES = {}
_chapter = 0
_fig_n = _tbl_n = 0

doc = Document()
_normal = doc.styles["Normal"]
_normal.font.name = FONT
_normal.font.size = Pt(BODY)
_normal.element.rPr.rFonts.set(qn("w:eastAsia"), FONT)
_normal.paragraph_format.line_spacing = LINE
_normal.paragraph_format.alignment = WD_ALIGN_PARAGRAPH.JUSTIFY
_normal.paragraph_format.space_after = Pt(0)
_normal.paragraph_format.space_before = Pt(0)

for s in doc.sections:
    s.left_margin = s.right_margin = s.top_margin = s.bottom_margin = Inches(MARGIN)


def _field(paragraph, instr):
    r = paragraph.add_run()
    for tag, attr in (("begin", None), (None, instr), ("separate", None), ("end", None)):
        if attr is not None:
            el = OxmlElement("w:instrText")
            el.set(qn("xml:space"), "preserve")
            el.text = attr
        else:
            el = OxmlElement("w:fldChar")
            el.set(qn("w:fldCharType"), tag)
        r._r.append(el)


def _page_number_format(section, fmt, start):
    sect_pr = section._sectPr
    el = sect_pr.find(qn("w:pgNumType"))
    if el is None:
        el = OxmlElement("w:pgNumType")
        sect_pr.append(el)
    el.set(qn("w:fmt"), fmt)
    el.set(qn("w:start"), str(start))


def start_body_numbering():
    """Front matter runs i, ii, iii...; the body restarts at 1 in Arabic."""
    sec = doc.add_section(WD_SECTION.NEW_PAGE)
    sec.left_margin = sec.right_margin = sec.top_margin = sec.bottom_margin = Inches(MARGIN)
    _page_number_format(sec, "decimal", 1)
    return sec


def page_numbers():
    _page_number_format(doc.sections[0], "lowerRoman", 1)
    # The title page carries no number, which is what a separate first-page
    # footer gives us — it is left empty.
    doc.sections[0].different_first_page_header_footer = True
    for i, s in enumerate(doc.sections):
        if i:
            s.footer.is_linked_to_previous = False
        p = s.footer.paragraphs[0]
        p.alignment = WD_ALIGN_PARAGRAPH.CENTER
        p.paragraph_format.line_spacing = LINE
        p.paragraph_format.space_after = Pt(0)
        _field(p, "PAGE")
        for r in p.runs:
            r.font.name, r.font.size = FONT, Pt(11)


def refresh_fields_on_open():
    el = OxmlElement("w:updateFields")
    el.set(qn("w:val"), "true")
    doc.settings.element.append(el)


def para(text="", size=BODY, bold=False, align=WD_ALIGN_PARAGRAPH.JUSTIFY,
         after=6, italic=False, indent=0.0, spacing=LINE):
    p = doc.add_paragraph()
    p.alignment = align
    p.paragraph_format.space_after = Pt(after)
    p.paragraph_format.space_before = Pt(0)
    p.paragraph_format.line_spacing = spacing
    if indent:
        p.paragraph_format.left_indent = Inches(indent)
    if text:
        r = p.add_run(text)
        r.font.size, r.bold, r.italic, r.font.name = Pt(size), bold, italic, FONT
    return p


def new_page():
    doc.add_paragraph().add_run().add_break(WD_BREAK.PAGE)


def chapter(title, numbered=True, new_page_first=True):
    """Chapter heading: own page, centred, 16 pt bold."""
    global _chapter, _fig_n, _tbl_n
    if new_page_first:      # a section break has already turned the page
        new_page()
    if numbered:
        _chapter += 1
        _fig_n = _tbl_n = 0
        text = f"CHAPTER {_chapter}: {title.upper()}"
    else:
        text = title.upper()
    p = doc.add_paragraph(style="Heading 1")
    p.alignment = WD_ALIGN_PARAGRAPH.CENTER
    p.paragraph_format.space_before = Pt(0)
    p.paragraph_format.space_after = Pt(14)
    p.paragraph_format.line_spacing = LINE
    r = p.add_run(text)
    r.font.size, r.bold, r.font.color.rgb, r.font.name = Pt(CHAP), True, INK, FONT
    contents.append((1, text))
    return p


def section(title):
    p = doc.add_paragraph(style="Heading 2")
    p.alignment = WD_ALIGN_PARAGRAPH.LEFT
    p.paragraph_format.space_before = Pt(10)
    p.paragraph_format.space_after = Pt(6)
    p.paragraph_format.line_spacing = LINE
    p.paragraph_format.keep_with_next = True
    r = p.add_run(title)
    r.font.size, r.bold, r.font.color.rgb, r.font.name = Pt(SUB), True, INK, FONT
    contents.append((2, title))
    return p


def bullet(text, indent=0.35):
    # "List Bullet" carries the bullet glyph; "List Paragraph" is just an indent.
    p = doc.add_paragraph(style="List Bullet")
    p.paragraph_format.left_indent = Inches(indent)
    p.paragraph_format.space_after = Pt(3)
    p.paragraph_format.space_before = Pt(0)
    p.paragraph_format.line_spacing = LINE
    p.alignment = WD_ALIGN_PARAGRAPH.JUSTIFY
    r = p.add_run(text)
    r.font.size, r.font.name = Pt(BODY), FONT
    return p


def figure(png, title):
    """Embed a rendered diagram with a chapter-scoped caption."""
    global _fig_n
    _fig_n += 1
    label = f"Figure {_chapter}.{_fig_n}"
    path = png if os.path.isabs(png) else os.path.join(DIAGRAMS, png)
    with Image.open(path) as im:
        w_px, h_px = im.size
    width = USABLE_W
    if width * h_px / w_px > MAX_FIG_H:
        width = MAX_FIG_H * w_px / h_px
    doc.add_picture(path, width=Inches(width))
    pic = doc.paragraphs[-1]
    pic.alignment = WD_ALIGN_PARAGRAPH.CENTER
    pic.paragraph_format.space_before = Pt(6)
    pic.paragraph_format.space_after = Pt(2)
    para(f"{label}: {title}", size=11, bold=True,
         align=WD_ALIGN_PARAGRAPH.CENTER, after=10, spacing=LINE)
    figures.append((label, title))


def table(title, headers, rows, widths=None, size=10.5):
    """Caption above the table, centred bold headers, no fill, and columns sized
    to their contents so a narrow column does not hold a gap open beside it."""
    global _tbl_n
    _tbl_n += 1
    label = f"Table {_chapter}.{_tbl_n}"
    caption = para(f"{label}: {title}", size=11, bold=True,
                   align=WD_ALIGN_PARAGRAPH.CENTER, after=4, spacing=LINE)
    caption.paragraph_format.keep_with_next = True
    t = doc.add_table(rows=1, cols=len(headers))
    t.style = "Table Grid"
    t.alignment = WD_TABLE_ALIGNMENT.CENTER
    t.autofit = True
    for i, h in enumerate(headers):
        c = t.rows[0].cells[i]
        c.text = ""
        p = c.paragraphs[0]
        p.alignment = WD_ALIGN_PARAGRAPH.CENTER
        p.paragraph_format.line_spacing = LINE
        p.paragraph_format.space_after = Pt(2)
        p.paragraph_format.space_before = Pt(2)
        r = p.add_run(h)
        r.bold, r.font.size, r.font.name = True, Pt(size), FONT
    for row in rows:
        cells = t.add_row().cells
        for i, v in enumerate(row):
            cells[i].text = ""
            p = cells[i].paragraphs[0]
            p.paragraph_format.line_spacing = LINE
            p.paragraph_format.space_after = Pt(2)
            p.paragraph_format.space_before = Pt(2)
            r = p.add_run(str(v))
            r.font.size, r.font.name = Pt(size), FONT
    _apply_widths(t, _column_widths(headers, rows, size))
    keep_on_one_page(t)
    para("", after=10, spacing=LINE)
    tables.append((label, title))
    if rows:
        # The longest word of each end row: a whole word survives the wrapping
        # that the PDF text extractor applies, where a whole cell may not.
        table_spans[label] = [_row_text(rows[0]), _row_text(rows[-1])]
    return t


MAX_COL = 3.1                    # inches
CELL_PADDING = 0.17              # Word's default left+right cell margins
FONT_FILES = {
    False: "/System/Library/Fonts/Supplemental/Times New Roman.ttf",
    True: "/System/Library/Fonts/Supplemental/Times New Roman Bold.ttf",
}
_MEASURED = 200                  # measure at a large size, then scale down
_fonts = {}


def text_width(text, size, bold=False):
    """Width of `text` in inches, measured from the font rather than guessed.

    Estimating from a character count put "IPAddress" and "Transaction" in
    columns too narrow to hold them, and Word broke the words in half.
    """
    font = _fonts.get(bold)
    if font is None:
        font = _fonts[bold] = ImageFont.truetype(FONT_FILES[bold], _MEASURED)
    return font.getlength(text) / _MEASURED * size / 72


def _column_widths(headers, rows, size):
    """Width each column by what it holds, so a column of short values takes
    only the room it needs and the column beside it starts further left.

    Word's own autofit is advisory — LibreOffice renders the columns evenly
    regardless — so the widths are computed here and written as fixed values.
    Each column's floor is its longest single word, so nothing is ever broken
    mid-word; only the slack above that floor is given up when a table is wider
    than the text column.
    """
    bounds = []
    for i, header in enumerate(headers):
        cells = [str(r[i]) for r in rows]
        words = [w for cell in cells for w in cell.split()] or [""]
        low = max([text_width(w, size) for w in words]
                  + [text_width(header, size, bold=True)]) + CELL_PADDING
        high = max([text_width(cell, size) for cell in cells] + [low - CELL_PADDING])
        bounds.append((low, min(max(high + CELL_PADDING, low), max(MAX_COL, low))))

    total = sum(high for _, high in bounds)
    if total <= USABLE_W:
        return [high for _, high in bounds]       # narrower than the page: fine
    room = sum(high - low for low, high in bounds)
    if room <= 0:                                  # nothing left to give back
        return [USABLE_W * high / total for _, high in bounds]
    over = min(total - USABLE_W, room)
    return [high - (high - low) * over / room for low, high in bounds]


def _row_text(row):
    """The first cell's first token, as a unique page-location anchor. Three
    approaches broke before this one: the longest word across the whole row
    collided when rows shared a module name; concatenating every cell broke
    because pdftotext -layout emits wrapped columns in physical reading
    order, not logical cell order, so the concatenation never matched; and
    even a whole first cell can itself wrap onto two lines when it is long
    (e.g. "velocity:<account_id> member"). A single leading token is short
    enough to never wrap on its own, and distinct enough within one table to
    tell its first row from its last."""
    return str(row[0]).split()[0] if str(row[0]).split() else str(row[0])


def keep_on_one_page(t):
    """Stop a table being split across a page boundary.

    Word has no "keep this table together" property, so the effect is built from
    the two that do exist: no row may break internally, and every row but the
    last is kept with the row after it. If a table is taller than the text area
    it must still break somewhere — the header row is marked to repeat so that
    the continuation is at least readable.
    """
    for row in t.rows:
        row._tr.get_or_add_trPr().append(OxmlElement("w:cantSplit"))
    for row in t.rows[:-1]:
        for cell in row.cells:
            for p in cell.paragraphs:
                p.paragraph_format.keep_with_next = True
    t.rows[0]._tr.get_or_add_trPr().append(OxmlElement("w:tblHeader"))


def _apply_widths(t, widths):
    t.autofit = False
    tbl_pr = t._tbl.tblPr
    for tag in ("w:tblW", "w:tblLayout"):
        el = tbl_pr.find(qn(tag))
        if el is not None:
            tbl_pr.remove(el)
    total = OxmlElement("w:tblW")
    total.set(qn("w:w"), str(int(sum(widths) * 1440)))
    total.set(qn("w:type"), "dxa")
    tbl_pr.append(total)
    layout = OxmlElement("w:tblLayout")
    layout.set(qn("w:type"), "fixed")
    tbl_pr.append(layout)
    for col, width in zip(t._tbl.tblGrid.findall(qn("w:gridCol")), widths):
        col.set(qn("w:w"), str(int(width * 1440)))
    for i, width in enumerate(widths):
        for row in t.rows:
            row.cells[i].width = Inches(width)


def code_block(lines, size=9):
    t = doc.add_table(rows=1, cols=1)
    t.style = "Table Grid"
    cell = t.cell(0, 0)
    cell.text = ""
    for i, line in enumerate(lines.split("\n")):
        p = cell.paragraphs[0] if i == 0 else cell.add_paragraph()
        p.paragraph_format.space_after = Pt(0)
        p.paragraph_format.line_spacing = LINE
        r = p.add_run(line if line else " ")
        r.font.name, r.font.size = "Consolas", Pt(size)
    para("", after=8)


# ───────────────────────── FRONT MATTER ─────────────────────────
para("SOFTWARE REQUIREMENTS SPECIFICATION", CHAP, True, WD_ALIGN_PARAGRAPH.CENTER, 10)
para("INDUS11 — AI FINANCIAL RISK AND FRAUD DECISION ENGINE", CHAP, True,
     WD_ALIGN_PARAGRAPH.CENTER, 20)
para("A Software Group Project Report", BODY, False, WD_ALIGN_PARAGRAPH.CENTER, 4)
para("Semester 5   |   Academic Year 2026-27   |   Project ID: PRJ_CE_5_2026_7",
     BODY, False, WD_ALIGN_PARAGRAPH.CENTER, 20)
para("Submitted by", BODY, True, WD_ALIGN_PARAGRAPH.CENTER, 6)
for n, sid in [("Joshi Om", "24DCE052"), ("Krish Gajera", "24DCE040"),
               ("Drashti Dedaniya", "24DCE029")]:
    para(f"{n}   ({sid})", BODY, False, WD_ALIGN_PARAGRAPH.CENTER, 2)
para("", after=16)
para("Under the guidance of", BODY, False, WD_ALIGN_PARAGRAPH.CENTER, 4)
para("Dr. Deven Gol", BODY, True, WD_ALIGN_PARAGRAPH.CENTER, 2)
para("Assistant Professor, Department of Computer Engineering", BODY, False,
     WD_ALIGN_PARAGRAPH.CENTER, 20)
para("DEVANG PATEL INSTITUTE OF ADVANCE TECHNOLOGY AND RESEARCH (DEPSTAR)",
     BODY, True, WD_ALIGN_PARAGRAPH.CENTER, 3)
para("CHAROTAR UNIVERSITY OF SCIENCE AND TECHNOLOGY (CHARUSAT)", BODY, True,
     WD_ALIGN_PARAGRAPH.CENTER, 3)
para("Changa, Gujarat — 388421", BODY, False, WD_ALIGN_PARAGRAPH.CENTER)

new_page()
para("CERTIFICATE", CHAP, True, WD_ALIGN_PARAGRAPH.CENTER, 18)
para("This is to certify that the Software Requirements Specification entitled "
     "“Indus11 — AI Financial Risk and Fraud Decision Engine” is the bona fide work "
     "carried out by Joshi Om (24DCE052), Krish Gajera (24DCE040) and Drashti "
     "Dedaniya (24DCE029) of Semester 5, Department of Computer Engineering, DEPSTAR, "
     "CHARUSAT, in partial fulfilment of the requirements of the Software Group "
     "Project during the academic year 2026-27.", after=48)
_c = doc.add_table(rows=1, cols=2)
for i, txt in enumerate(["Dr. Deven Gol\nInternal Guide\nAssistant Professor\n"
                         "Computer Engineering",
                         "Head of Department\nComputer Engineering\n"
                         "DEPSTAR, CHARUSAT"]):
    cell = _c.cell(0, i)
    cell.text = ""
    p = cell.paragraphs[0]
    p.paragraph_format.line_spacing = LINE
    p.paragraph_format.space_after = Pt(0)
    r = p.add_run(txt)
    r.font.size, r.font.name = Pt(BODY), FONT
    cell.width = Inches(3.0)
para("", after=10)
para("Date: ______________                    Place: Changa")

new_page()
para("ACKNOWLEDGEMENT", CHAP, True, WD_ALIGN_PARAGRAPH.CENTER, 18)
para("The satisfaction that accompanies the successful completion of any task would be "
     "incomplete without mentioning the people who made it possible, and whose constant "
     "guidance and encouragement crowned our effort with success.", after=10)
para("We are deeply indebted to our internal guide, Dr. Deven Gol, Assistant Professor, "
     "Department of Computer Engineering, DEPSTAR, for his valuable guidance, his "
     "patience with our drafts and the detailed review comments that shaped both this "
     "project and this document. His insistence on measured results rather than claims "
     "has improved our work considerably.", after=10)
para("We extend our sincere thanks to the Head of the Department of Computer "
     "Engineering and to the Principal of Devang Patel Institute of Advance Technology "
     "and Research (DEPSTAR) for providing us with the laboratory facilities, the "
     "academic environment and the freedom to pursue this problem.", after=10)
para("We are thankful to the faculty members of the Department of Computer Engineering "
     "for the foundation in databases, software engineering and machine learning on "
     "which this project rests, and to our classmates for their review and testing of "
     "our early prototypes.", after=10)
para("We also acknowledge the open-source communities behind FastAPI, MongoDB, Neo4j, "
     "Redis, ChromaDB, LangChain, Ollama and React, and the authors of the research "
     "cited in this report, whose work made a project of this scope possible within a "
     "single semester.", after=10)
para("Finally, we thank our parents and families for their constant support and "
     "encouragement throughout the course of this work.", after=24)
for n, sid in [("Joshi Om", "24DCE052"), ("Krish Gajera", "24DCE040"),
               ("Drashti Dedaniya", "24DCE029")]:
    para(f"{n} ({sid})", align=WD_ALIGN_PARAGRAPH.RIGHT, after=2)

new_page()
para("ABSTRACT", CHAP, True, WD_ALIGN_PARAGRAPH.CENTER, 18)
para("Indus11 is an AI-powered financial fraud detection and decision support system "
     "developed to identify suspicious banking transactions using a multi-layer risk "
     "assessment approach. The system addresses the limitations of conventional "
     "rule-based fraud detection by combining deterministic rules, graph-based "
     "relationship analysis, and Retrieval-Augmented Generation (RAG) to produce "
     "explainable risk decisions.")
para("The application is implemented using Python 3.12 and FastAPI for the backend "
     "APIs, React for the analyst dashboard, MongoDB (Beanie ODM) for transactional "
     "data storage, Neo4j for relationship analysis, Redis for caching, and ChromaDB "
     "as the vector database for document retrieval. LangChain and Ollama integrate "
     "the Large Language Model with the RAG pipeline, enabling the system to retrieve "
     "relevant banking policies, fraud guidelines, and historical cases before "
     "generating contextual explanations for analysts.")
para("Incoming transactions are evaluated through a three-layer scoring pipeline. The "
     "rule engine contributes 0–40 risk points based on predefined fraud indicators, "
     "graph analysis contributes 0–30 points by detecting shared devices, IP "
     "addresses, and circular transaction flows among accounts, while the RAG-based "
     "reasoning module contributes 0–30 points by validating contextual evidence. The "
     "combined score determines whether a transaction is classified as APPROVE, "
     "REVIEW, or BLOCK, while providing an explanation for every decision.")
para("The system was evaluated using a labelled fraud dataset and achieved 93.8% "
     "precision, 86.5% recall, and an F1-score of 0.90. Graph analysis successfully "
     "identified all 36 transactions belonging to the 3 planted mule rings, "
     "demonstrating the effectiveness of relationship-based fraud detection. During "
     "evaluation, no transaction reached the predefined BLOCK threshold because the "
     "seeded fraud accounts lacked stored historical profiles, preventing the "
     "amount-anomaly rule from contributing to their overall score. This identified a "
     "limitation in the current scoring mechanism rather than a characteristic of the "
     "dataset and highlights an area for future enhancement. Overall, the results "
     "demonstrate that integrating rule-based analysis, graph analytics, and "
     "RAG-based reasoning improves fraud detection while maintaining explainability "
     "and supporting financial investigators in making informed decisions.", after=10)
para("Keywords: fraud detection, explainable AI, graph analytics, retrieval-augmented "
     "generation, risk scoring", italic=True)

new_page()
TOC_ANCHOR = doc.add_paragraph()

new_page()
LOF_ANCHOR = doc.add_paragraph()
new_page()                      # the list of tables starts on its own page
LOT_ANCHOR = doc.add_paragraph()

# Front matter is not produced by chapter()/section(), so it is listed by hand.
FRONT_MATTER = ["CERTIFICATE", "ACKNOWLEDGEMENT", "ABSTRACT",
                "LIST OF FIGURES", "LIST OF TABLES"]

# ───────────────────────── CHAPTER 1 ─────────────────────────
start_body_numbering()
chapter("Introduction", new_page_first=False)
section("1.1 Purpose")
para("This document specifies the software requirements for Indus11, a real-time "
     "financial fraud detection and decision engine. It states what the system must "
     "do, the interfaces it exposes, the constraints it operates under and the quality "
     "attributes against which it is measured.")
para("The intended readers are the project team, the internal guide and the evaluation "
     "panel, and any developer who later integrates with or extends the system. Every "
     "measured figure quoted in this document comes from an executed benchmark run "
     "rather than an estimate. The arrangement of the sections follows the structure "
     "recommended for a software requirements specification in IEEE Std 830-1998 [1].")
section("1.2 Scope")
para("Indus11 accepts one financial transaction over a REST interface, analyses it "
     "with three independent detection engines and returns a composite risk score from "
     "0 to 100, a decision of APPROVE, REVIEW or BLOCK, and a plain-language "
     "explanation. A web dashboard allows an analyst to view live statistics, inspect "
     "any flagged transaction and override a review outcome.")
para("The following are outside the scope of the system: it does not move money or "
     "settle payments; it is not a core banking system; it processes synthetic data "
     "only; it performs no regulatory reporting; and the training of a supervised "
     "model is identified as future work.")
section("1.3 Document Overview")
para("Chapter 2 describes the system as a whole. Chapter 3 states the functional, "
     "non-functional and security requirements. Chapter 4 presents the system design "
     "and data flow. Chapter 5 contains the UML models. Chapter 6 specifies the "
     "database design. The conclusion, the references and the list of definitions and "
     "acronyms follow at the end of the document.")

# ───────────────────────── CHAPTER 2 ─────────────────────────
chapter("Overall Description")
section("2.1 Product Perspective")
para("Indus11 is a new, self-contained decision service rather than a replacement for "
     "an existing product. In a production setting it would sit beside a payment "
     "processor: the processor submits a transaction and acts on the returned "
     "decision. Commercial platforms occupy the same position in a payment flow — FICO "
     "Falcon Fraud Manager [6], the Feedzai RiskOps platform [7] and Featurespace ARIC "
     "Risk Hub [8] — and the distinguishing aim here is that the reasons for a decision "
     "are returned with it rather than held inside the model.")
para("The system comprises a FastAPI application [10], a React dashboard and four data "
     "stores, each with a distinct role — MongoDB for account profiles and the audit "
     "trail, reached through the Beanie object-document mapper [11]; Neo4j for the "
     "transaction graph; Redis for caching and the velocity window; and ChromaDB for "
     "the fraud-pattern knowledge base, retrieved through LangChain [12].")
section("2.2 Product Functions")
for fn in ["Accept and validate a transaction over a documented REST interface.",
           "Load account profiles from cache, falling back to the document store.",
           "Score the transaction against configurable rules, including a "
           "rolling-window velocity check.",
           "Detect fraud rings and shared-identity clusters in the transaction graph.",
           "Retrieve similar fraud patterns and generate a natural-language explanation.",
           "Combine the layer scores into one score and map it to a decision.",
           "Persist every analysis so that decisions can be audited.",
           "Present live statistics and flagged transactions on a dashboard.",
           "Allow an analyst to inspect a transaction and override a review decision.",
           "Measure detection accuracy against a labelled dataset.",
           "Protect the service with per-client rate limiting."]:
    bullet(fn)
section("2.3 User Characteristics")
table("User classes and their characteristics", ["User class", "Characteristics"],
      [["Fraud analyst", "Primary user. Reviews and acts on flagged transactions. "
                         "Understands fraud typologies but does not read code or write "
                         "queries, so each decision must be explained in plain language."],
       ["System administrator", "Deploys and operates the stack, tunes thresholds and "
                                "runs the seed and evaluation scripts."],
       ["Integrating developer", "Consumes the REST interface from a payment system. "
                                 "Requires accurate schemas and documented status codes."],
       ["Project evaluator", "Assesses the system against this specification and "
                             "reproduces the measured results."]],
      widths=[1.5, 4.5])
section("2.4 Operating Environment")
table("Operating environment", ["Element", "Requirement"],
      [["Hardware", "64-bit x86 or ARM machine, 8 GB RAM minimum, approximately 5 GB "
                    "free disk space. No graphics processor is required."],
       ["Operating system", "Linux, macOS or Windows with Docker support."],
       ["Runtime", "Python 3.12 for the backend, Node.js 20 for the dashboard build."],
       ["Databases", "MongoDB 7, Neo4j 5.20 Community Edition, Redis 7.2, ChromaDB."],
       ["Language model", "Ollama running llama3 locally, or the OpenAI service."],
       ["Client", "Any modern browser at 1280 pixels width or greater."]],
      widths=[1.4, 4.6])
section("2.5 Design Constraints")
for c in ["The system shall run in full on a single machine without a graphics processor.",
          "No real customer or payment data may be used; all datasets are synthetic.",
          "The language model shall contribute no more than 30 of the 100 points.",
          "The language model shall be able to run locally, at no external cost.",
          "The backend shall be written in Python 3.12 and the dashboard in React.",
          "Neo4j Community Edition is used, so enterprise-only features are unavailable.",
          "The sum of all layer score budgets shall equal 100.",
          "Credentials shall never be committed to version control."]:
    bullet(c)
section("2.6 Assumptions and Dependencies")
for a in ["The four data stores are reachable. If a store is unavailable the affected "
          "layer degrades rather than failing the request.",
          "A local language model or an external service key is available. Without "
          "either, the rule and graph layers still produce a decision and only the "
          "written explanation is lost.",
          "The synthetic dataset is representative enough to compare configurations "
          "against one another, but not to predict production accuracy: fraud is far "
          "denser in it than in a real payment feed, so the measured precision is "
          "optimistic.",
          "An account with no stored profile is treated as elevated risk rather than "
          "as safe.",
          "Decision thresholds are tunable for each deployment; the values quoted in "
          "this document are the defaults.",
          "Any change to a layer's score budget would require the thresholds and the "
          "accuracy baseline to be derived again."]:
    bullet(a)

# ───────────────────────── CHAPTER 3 ─────────────────────────
chapter("System Requirements")
section("3.1 Functional Requirements")
para("Each requirement is traceable to the module that implements it. The requirements "
     "are given in three tables — request handling and scoring, decision and "
     "persistence, then the surrounding accounts, graph, reporting and operations "
     "services — sized so that none has to run across a page break.")
table("Functional requirements — request handling and scoring",
      ["ID", "Requirement", "Module"],
      [["FR-1", "Accept a transaction over HTTP POST carrying identifier, sender, receiver, amount, currency and optional merchant, device, address and note fields.", "routes/transactions"],
       ["FR-2", "Validate every request against a schema and reject a malformed or non-positive amount before any analysis is performed.", "schemas/transaction"],
       ["FR-3", "Reject a duplicate transaction identifier with a conflict response so that a retried request does not produce a server error.", "routes/transactions"],
       ["FR-4", "Load sender and receiver profiles from cache, falling back to the document store, treating an unknown account as elevated risk.", "routes/transactions"],
       ["FR-5", "Score from 0 to 40 using blacklist, velocity, amount-anomaly, merchant and risk-tier rules, returning the reason for each rule that fired; return the maximum score immediately when either party is blacklisted.", "services/rule_engine"],
       ["FR-6", "Count transactions for an account within an exact ten-minute rolling window and flag more than five.", "core/redis_client"],
       ["FR-7", "Score from 0 to 30 by detecting shared devices, circular flows within four hops, fee-skimming chains and proximity to a known fraud cluster.", "services/graph_analyzer"],
       ["FR-8", "Record the transaction, its accounts, device and address in the graph so later transactions can be evaluated against it.", "services/graph_analyzer"],
       ["FR-9", "Retrieve similar fraud patterns and obtain a score from 0 to 30 with an explanation from the language model, degrading to a zero score with a stated reason when no language model is reachable.", "services/rag_pipeline"]],
      widths=[0.5, 4.2, 1.3], size=9)
table("Functional requirements — decision and persistence",
      ["ID", "Requirement", "Module"],
      [["FR-10", "Execute the rule and graph layers concurrently and return the decision from those two; score the retrieval and language-model layer after the response and fold its result into the stored record.", "routes/transactions"],
       ["FR-11", "Compute the composite score as the sum of the layer scores, clamped to 100.", "services/decision_engine"],
       ["FR-12", "Map the composite score to APPROVE, REVIEW or BLOCK using configured thresholds.", "services/decision_engine"],
       ["FR-13", "Include the triggered signals and the model's reasoning in every response.", "services/decision_engine"],
       ["FR-14", "Persist every analysed transaction with its score, decision, explanation and note.", "models/transaction"],
       ["FR-15", "Return a previously analysed transaction by identifier, or a not-found response.", "routes/transactions"],
       ["FR-16", "List recent transactions, optionally filtered by decision.", "routes/transactions"],
       ["FR-17", "Allow an analyst to override a decision and reject any invalid value.", "routes/transactions"],
       ["FR-17a", "Mark a transaction whose language-model assessment is still outstanding, and clear the mark when it completes or fails.", "routes/transactions"]],
      widths=[0.5, 4.2, 1.3], size=9)
table("Functional requirements — accounts, graph, reporting and operations",
      ["ID", "Requirement", "Module"],
      [["FR-18", "Support creating and listing accounts and toggling blacklist status.", "routes/accounts"],
       ["FR-19", "Return the graph neighbourhood of an account to a depth of one to three hops.", "routes/graph"],
       ["FR-20", "Propagate fraud labels to accounts within two hops and assign a cluster identifier.", "services/graph_analyzer"],
       ["FR-21", "Report graph statistics for accounts, devices, addresses, transactions and labels.", "routes/graph"],
       ["FR-22", "Report dashboard statistics: decision counts and score histogram, the most recent review/block transactions, and the latest accuracy results.", "routes/stats"],
       ["FR-23", "Replay a labelled dataset and report precision, recall, F1, a confusion matrix and ring detection.", "scripts/evaluate"],
       ["FR-24", "Derive decisions again across candidate thresholds and report no block threshold when none is reachable.", "scripts/evaluate"],
       ["FR-25", "Limit each client to 120 requests per minute overall and 30 on the analysis endpoint.", "core/rate_limit"],
       ["FR-26", "Expose a health endpoint reporting service status.", "routes/health"],
       ["FR-27", "Provide repeatable seed scripts for account profiles and a synthetic fraud graph.", "scripts/seed"],
       ["FR-28", "Display metrics, decision mix, score distribution, accuracy and flagged transactions with detail and override.", "dashboard"],
       ["FR-29", "Require a shared key on the routes that override a decision, change blacklist status or propagate fraud labels.", "core/security"],
       ["FR-30", "Restrict the graph layer's circular-flow detection to hops occurring within a configured window and in chronological order.", "services/graph_analyzer"],
       ["FR-31", "Withhold a written explanation that does not reference any triggered signal, and show the signal list alone in its place.", "services/decision_engine"],
       ["FR-32", "Show an outstanding language-model assessment on the dashboard and replace it with the final score when it arrives.", "dashboard"]],
      widths=[0.5, 4.2, 1.3], size=9)
section("3.2 Non-Functional Requirements")
para("Non-functional requirements are grouped below under performance, reliability, "
     "maintainability, testability, portability, usability and accuracy. Security "
     "requirements are stated separately in section 3.3.")
para("Performance. The values below were measured on the development machine, an "
     "Apple Silicon computer running without a graphics processor, and are reproduced by "
     "the commands in Appendix B.")
para("An earlier revision of this document reported a complete-pipeline latency of "
     "14,046 milliseconds, of which about 13.9 seconds was the language model. That "
     "measurement was taken when the language model was still inside the decision "
     "path. Following the first project review it was moved out of it, and the "
     "figures below are the current measurements.")
table("Measured performance", ["Measurement", "Value", "Note"],
      [["Rule engine", "8 ms", "Velocity check and in-memory rules."],
       ["Graph analyzer", "20 ms", "Graph write and four pattern queries, time-windowed."],
       ["Response, mean", "124 ms", "Rule and graph layers, measured over 29 requests."],
       ["Response, 95th percentile", "189 ms", "Slowest 1 request in 20."],
       ["Response, maximum", "287 ms", "Worst observed sample."],
       ["Within the 500 ms budget", "29 of 29", "Every sampled request."],
       ["Language model", "13-14 s", "Runs after the response, not inside it."]],
      widths=[1.9, 1.6, 2.5])
for n in ["The deterministic layers shall complete within 500 milliseconds per transaction.",
          "The rule and graph layers shall run concurrently, so that the response "
          "latency is bounded by the slower of the two rather than by their sum.",
          "The retrieval and language-model layer shall not delay the response. It is "
          "scored after the response has been returned, and its score and written "
          "explanation are added to the stored record when they are ready.",
          "A transaction whose language-model assessment is still outstanding shall be "
          "marked as such, so that a provisional decision is never mistaken for a "
          "final one.",
          "An identical transaction submitted twice shall receive an identical score. "
          "The language model is therefore configured at temperature zero; at the "
          "default setting the same transaction was measured scoring between 20 and "
          "26."]:
    bullet(n)
para("Reliability and maintainability.")
for n in ["The service shall hold no state between requests, so that an instance can be "
          "restarted without loss of data.",
          "An unavailable component shall never cause a transaction to be approved silently.",
          "The composite score shall be clamped so that no combination exceeds the range.",
          "Every decision shall be persisted with its explanation for audit."]:
    bullet(n)
para("Testability and portability.")
for n in ["The automated test suite shall run without any database or network access.",
          "The stack shall start with a single command on Linux, macOS or Windows."]:
    bullet(n)
table("Software quality attributes", ["Attribute", "How it is achieved"],
      [["Reliability", "The pipeline degrades one component at a time; a duplicate "
                       "submission returns a defined conflict response."],
       ["Maintainability", "Each layer is a single function with one input and one "
                           "output type, so a layer can be replaced independently."],
       ["Testability", "Thirty-six automated tests run with no database or network."],
       ["Portability", "The entire stack is defined in one container composition file."],
       ["Usability", "Every decision is accompanied by a written explanation."],
       ["Accuracy", f"Precision {FLAGGED['precision']:.3f}, recall {FLAGGED['recall']:.3f}, "
                    f"F1 {FLAGGED['f1']:.3f} over {COUNTS['total']} transactions; "
                    f"{GRAPH['graph_flagged']} of {GRAPH['ring_transactions']} ring "
                    "transactions detected."]],
      widths=[1.3, 4.7])
section("3.3 Security Requirements")
for s in ["Credentials shall be supplied through environment variables and never committed.",
          "All input shall be validated against a strict schema before use.",
          "Database access shall use parameterised queries throughout.",
          "Rate limiting shall be applied for each client address.",
          "Stored explanations shall be truncated to a bounded length.",
          "Account identifiers are the only data shared between stores; no payment "
          "instrument data is persisted.",
          "The routes that alter a stored decision, change an account's blacklist "
          "status or rewrite the graph's fraud labels shall require a shared key "
          "supplied in a request header, compared in constant time.",
          "Browser access shall be restricted to configured origins rather than "
          "permitted from any origin.",
          "Fields that are incorporated into a language-model prompt shall be "
          "constrained to a fixed vocabulary or a bounded length, so that submitted "
          "text cannot be used to redirect the model's assessment.",
          "Full user authentication and authorisation are not implemented in the "
          "current version. The shared-key check above covers the routes whose misuse "
          "would alter a decision; per-user authentication remains recorded as future "
          "work, and the interface is intended for a trusted network in the meantime."]:
    bullet(s)

# ───────────────────────── CHAPTER 4 ─────────────────────────
chapter("System Design")
section("4.1 Overall Architecture")
para("The system is organised as a five-layer pipeline. The first layer validates the "
     "request and loads context. The second and third layers, the rule engine and the "
     "graph analyzer, score the transaction concurrently, and the fifth layer "
     "aggregates their scores and determines the decision that is returned. The fourth "
     "layer, retrieval-augmented generation, is scored after the response has been "
     "sent and its result is folded into the stored record; it was moved out of the "
     "request path following the first project review, where its 13 to 14 second "
     "latency was identified as unacceptable inside a decision that a payment system "
     "must return in under a second.")
para("Two of the scoring layers are adapted from published work. The graph layer takes "
     "the network-based view of card-fraud detection set out by Van Vlasselaer and "
     "others [2] and the semi-supervised propagation of fraud labels across a "
     "transaction graph described by Lebichot and others [3]; the Cypher patterns "
     "themselves follow the fraud-detection recipes in the Neo4j developer "
     "documentation [9]. The fourth layer applies retrieval-augmented generation, in "
     "which documents retrieved from a knowledge base are supplied to a language model "
     "as context for its answer [5].")
figure("final-architecture.png", "System architecture — five-layer pipeline")
section("4.2 Context Diagram")
para("The context diagram shows the system as a single process together with the "
     "external entities that exchange data with it.")
figure("final-dfd0.png", "Data flow diagram — Level 0 (context diagram)")
section("4.3 Data Flow Diagram — Level 1")
para("The level 1 diagram decomposes the system into its seven principal processes and "
     "shows the data stores each process reads from and writes to.")
figure("final-dfd1.png", "Data flow diagram — Level 1")

# ───────────────────────── CHAPTER 5 ─────────────────────────
chapter("UML Diagrams")
section("5.1 Use Case Diagram")
para("The use case diagram identifies the three actors and the services each may invoke.")
figure("final-usecase.png", "Use case diagram")
section("5.2 Activity Diagram")
para("The activity diagram shows the workflow of a transaction across the participants, "
     "including the concurrent evaluation of the three scoring layers and the manual "
     "review path.")
figure("final-activity.png", "Activity diagram — transaction analysis workflow")
section("5.3 Class Diagram")
para("The class diagram shows the domain classes, the abstract analysis layer with its "
     "three concrete implementations, and the relationships between them.")
figure("final-class.png", "Class diagram — core domain and service classes")

# ───────────────────────── CHAPTER 6 ─────────────────────────
chapter("Database Design")
section("6.1 Logical Data Schema")
para("The document store is schemaless, so the schema below is the logical one enforced "
     "by the application: the Beanie document models declare the fields, their types and "
     "their indexes, and those indexes are created when the application starts, so no "
     "migration step is required. The two collections and their keys are given first, "
     "followed by the field-level definition of each.")
table("Collections, keys and indexes",
      ["Collection", "Primary key", "Unique index", "Secondary indexes", "Referenced by"],
      [["accounts", "_id (ObjectId)", "account_id", "—",
        "transactions (sender and receiver); Neo4j Account"],
       ["transactions", "_id (ObjectId)", "tx_id",
        "sender_account_id, receiver_account_id, decision",
        "Neo4j Transaction"]],
      widths=[0.9, 1.0, 0.9, 1.5, 1.7], size=9.5)
table("Accounts collection", ["Field", "Type", "Constraint", "Description"],
      [["account_id", "String", "Unique index", "Primary business key."],
       ["owner_name", "String", "Required", "Account holder name (synthetic)."],
       ["country_code", "String", "Default", "Two-letter country code."],
       ["avg_monthly_transaction", "Float", "Default 0.0", "Baseline for the anomaly rule."],
       ["is_blacklisted", "Boolean", "Default false", "Forces the maximum rule score."],
       ["risk_tier", "String", "Default standard", "One of standard, elevated or high."]],
      widths=[1.6, 0.9, 1.2, 2.3], size=10)
table("Transactions collection", ["Field", "Type", "Constraint", "Description"],
      [["tx_id", "String", "Unique index", "A duplicate insert is rejected."],
       ["sender_account_id", "String", "Indexed", "Supports per-account history."],
       ["receiver_account_id", "String", "Indexed", "Counterparty account."],
       ["amount", "Float", "Greater than 0", "Transaction value."],
       ["currency", "String", "Default INR", "Currency code."],
       ["merchant_category", "String", "Optional", "Drives the merchant rule."],
       ["device_id", "String", "Optional", "Identity signal for the graph layer."],
       ["ip_address", "String", "Optional", "Identity signal for the graph layer."],
       ["composite_score", "Integer", "0 to 100", "Final risk score."],
       ["decision", "String", "Indexed", "APPROVE, REVIEW or BLOCK."],
       ["explanation", "String", "Bounded length", "Signals and model reasoning."],
       ["note", "String", "Optional", "Free text supplied at submission."],
       ["created_at", "DateTime", "Default now", "Supports recent-first listing."]],
      widths=[1.6, 0.9, 1.2, 2.3], size=10)
section("6.2 Data Dictionary")
para("Every entity held outside the document store is defined below, one table per "
     "store. Together with the two collection tables above these cover all persisted "
     "data in the system.")
table("Graph node types (Neo4j)",
      ["Node label", "Properties", "Key", "Purpose"],
      [["Account", "account_id, risk_label, fraud_cluster", "account_id",
        "One vertex per party. risk_label carries fraud or fraud_adjacent and "
        "fraud_cluster names the seed account of the cluster."],
       ["Transaction", "tx_id, amount, timestamp", "tx_id",
        "One vertex per analysed transfer, retained as the graph-side record."],
       ["Device", "device_id", "device_id",
        "Shared-device identity signal, used to link otherwise unrelated accounts."],
       ["IPAddress", "address", "address",
        "Shared-address identity signal, used in the same way as Device."]],
      widths=[0.9, 1.7, 1.2, 2.2], size=9.5)
table("Graph relationship types (Neo4j)",
      ["Relationship", "From", "To", "Properties", "Purpose"],
      [["SENT", "Account", "Account", "tx_id, amount",
        "One money movement. Circular-flow and fee-skimming patterns are found "
        "by traversing two to four of these."],
       ["USED_DEVICE", "Account", "Device", "—",
        "Supports shared-device cluster detection."],
       ["USED_IP", "Account", "IPAddress", "—",
        "Supports shared-address cluster detection."],
       ["CONNECTED_TO", "Account", "Account", "—",
        "Materialised from a shared device or address; traversed by fraud label "
        "propagation to a depth of two."]],
      widths=[1.1, 0.9, 0.9, 1.1, 2.0], size=9.5)
table("Cache keys (Redis)",
      ["Key pattern", "Type", "Value", "Lifetime"],
      [["account:<account_id>", "String (JSON)", "Serialised account profile", "300 seconds"],
       ["velocity:<account_id>", "Sorted set",
        "Transaction timestamps scored by epoch second", "600 second rolling window"],
       ["velocity:<account_id> member", "String",
        "Event timestamp with a random suffix, so simultaneous events are distinct",
        "Aged out with its window"]],
      widths=[1.6, 1.1, 2.3, 1.0], size=9.5)
table("Vector store (ChromaDB)",
      ["Collection", "Field", "Type", "Description"],
      [["fraud_patterns", "id", "String", "Stable identifier of the pattern document."],
       ["fraud_patterns", "document", "Text",
        "Description of one fraud typology; 58 documents are seeded on startup."],
       ["fraud_patterns", "embedding", "Vector",
        "Embedding used for similarity retrieval by the RAG layer."],
       ["fraud_patterns", "metadata.category", "String",
        "Typology group, for example mule ring, card testing or account takeover."],
       ["fraud_patterns", "metadata.severity", "String",
        "Indicative severity, used to weight the retrieved context."]],
      widths=[1.2, 1.4, 0.9, 2.5], size=9.5)
para("Transaction records are retained indefinitely to preserve the audit trail, and no "
     "deletion path is exposed through the interface. Referential integrity between "
     "accounts and transactions is enforced by the application, since the document "
     "store does not impose foreign keys. Both seed scripts are idempotent.")
para("Indefinite retention has a consequence for the graph that was found by "
     "measurement rather than by reasoning. The circular-flow query originally matched "
     "any path returning to the sender across the whole retained history: 1,486 stored "
     "transactions produced 51,146 such paths, because any ordinary account that both "
     "sends and receives money eventually forms one. Almost half of that pattern's "
     "detections were on legitimate traffic as a result. The query is therefore "
     "restricted to hops falling within a bounded window and occurring in "
     "chronological order, which is the shape of a laundering chain rather than of "
     "ordinary commerce. Bounding the query is a separate decision from bounding "
     "storage, and only the former has been taken; an archival policy for the graph "
     "itself remains outstanding.")

# ────────────────── UNNUMBERED CLOSING SECTIONS ──────────────────
chapter("Conclusion and Future Enhancements", numbered=False)
para("Indus11 shows that detection capability and explainability need not be traded "
     "against one another, which is the trade-off reported for explainable ensemble "
     "methods in financial fraud detection [4]. Combining deterministic rules, graph "
     "traversal and a retrieval-augmented language model produced "
     f"{FLAGGED['precision']*100:.1f} per cent precision at "
     f"{FLAGGED['recall']*100:.1f} per cent recall on a labelled synthetic dataset of "
     f"{COUNTS['total']} transactions, while every decision carries the list of signals "
     "that caused it.")
para("The graph layer justified its inclusion. It detected all "
     f"{GRAPH['ring_transactions']} planted mule-ring transactions, which rules that "
     "examine a single transaction cannot detect by construction.")
para("The evaluation also produced a negative result worth recording. No transaction "
     "reached the configured block threshold, so nothing is blocked automatically and "
     "every detection reaches an analyst. Lowering the threshold would automate "
     "blocking at the cost of also blocking the false positives, which is a policy "
     "decision requiring evidence rather than a change of configuration.")
para("Planned enhancements, in order of priority:")
for e in ["Resolve the block-threshold trade-off using the recorded transaction scores.",
          "Extend the present shared-key check on the decision-altering routes to "
          "per-user authentication, and add structured request logging.",
          "Build an interactive fraud-ring visualisation on the existing graph endpoint.",
          "Investigate the seven undetected frauds and add fan-in and fan-out graph patterns.",
          "Train a supervised classifier as a fourth scoring signal.",
          "Bound the growth of the transaction graph with a retention or archival "
          "policy, so that query cost does not grow with the whole retained history.",
          "Validate against a public labelled dataset to obtain a realistic precision figure."]:
    bullet(e)

chapter("References", numbered=False)
para("Sources are listed in IEEE style and are referred to in the text by their number "
     "in square brackets.", after=10)
for i, r in enumerate([
    "IEEE, “IEEE Recommended Practice for Software Requirements Specifications,” "
    "IEEE Std 830-1998, Institute of Electrical and Electronics Engineers, 1998.",
    "V. Van Vlasselaer, C. Bravo, O. Caelen, T. Eliassi-Rad, L. Akoglu, M. Snoeck and "
    "B. Baesens, “APATE: A novel approach for automated credit card transaction fraud "
    "detection using network-based extensions,” Decision Support Systems, vol. 75, "
    "pp. 38–48, 2015.",
    "B. Lebichot, F. Braun, O. Caelen and M. Saerens, “A graph-based, semi-supervised, "
    "credit card fraud detection system,” in Complex Networks and Their Applications V, "
    "Springer, 2017, pp. 721–733.",
    "D. Vijayanand and G. S. Smrithy, “Explainable AI-enhanced ensemble learning for "
    "financial fraud detection,” 2025, doi:10.1177/18724981241289751.",
    "P. Lewis, E. Perez, A. Piktus, F. Petroni, V. Karpukhin and others, "
    "“Retrieval-augmented generation for knowledge-intensive NLP tasks,” Advances in "
    "Neural Information Processing Systems, vol. 33, pp. 9459–9474, 2020.",
    "FICO, “Falcon Fraud Manager,” product documentation, 2026. [Online]. "
    "Available: https://www.fico.com",
    "Feedzai, “RiskOps platform,” product overview, 2026. [Online]. "
    "Available: https://feedzai.com",
    "Featurespace, “ARIC Risk Hub,” product overview, 2026. [Online]. "
    "Available: https://www.featurespace.com",
    "Neo4j, “Graph algorithms for fraud detection,” developer documentation, 2026. "
    "[Online]. Available: https://neo4j.com/developer",
    "S. Ramirez, “FastAPI documentation,” 2026. [Online]. "
    "Available: https://fastapi.tiangolo.com",
    "MongoDB Inc., “MongoDB manual and Beanie ODM documentation,” 2026. [Online]. "
    "Available: https://www.mongodb.com/docs",
    "LangChain and Chroma documentation, 2026. [Online]. "
    "Available: https://python.langchain.com",
], 1):
    p = doc.add_paragraph()
    p.alignment = WD_ALIGN_PARAGRAPH.JUSTIFY
    p.paragraph_format.left_indent = Inches(0.4)
    p.paragraph_format.first_line_indent = Inches(-0.4)
    p.paragraph_format.line_spacing = LINE
    p.paragraph_format.space_after = Pt(6)
    run = p.add_run(f"[{i}]  {r}")
    run.font.size, run.font.name = Pt(BODY), FONT

chapter("Definitions, Acronyms and Abbreviations", numbered=False)

_DEFINITIONS = [
    ("API", "Application Programming Interface."),
    ("APPROVE", "Decision for a composite score of 0 to 39; the transaction proceeds."),
    ("BLOCK", "Decision for a composite score of 70 or above; the transaction is refused."),
    ("Composite score", "The sum of the three layer scores, clamped to 100."),
    ("Confusion matrix", "A table cross-tabulating the decision taken against the true label."),
    ("DFD", "Data Flow Diagram."),
    ("ER", "Entity Relationship."),
    ("F1", "The harmonic mean of precision and recall."),
    ("Fee skimming", "Each hop of a mule chain passing on slightly less money than it received."),
    ("Flag", "A signal code together with the values that triggered it."),
    ("HTTP", "Hypertext Transfer Protocol."),
    ("JSON", "JavaScript Object Notation."),
    ("Layer", "One stage of the analysis pipeline that produces a score and flags."),
    ("LLM", "Large Language Model."),
    ("Money-mule ring", "Accounts cycling funds among themselves to disguise the origin."),
    ("ODM", "Object-Document Mapper."),
    ("Precision", "Of the transactions flagged, the proportion genuinely fraudulent."),
    ("RAG", "Retrieval-Augmented Generation."),
    ("Recall", "Of the genuinely fraudulent transactions, the proportion flagged."),
    ("REST", "Representational State Transfer."),
    ("REVIEW", "Decision for a composite score of 40 to 69; held for a human analyst."),
    ("SRS", "Software Requirements Specification."),
    ("TTL", "Time To Live; the expiry period of a cached entry."),
    ("UML", "Unified Modeling Language."),
    ("Velocity", "The number of transactions an account makes inside a rolling window."),
]
# Split so neither half runs across a page break at 1.5 line spacing — one
# 25-row table doesn't fit a single page under the wider margins.
_HALF = (len(_DEFINITIONS) + 1) // 2
for _half in (_DEFINITIONS[:_HALF], _DEFINITIONS[_HALF:]):
    _t = doc.add_table(rows=1, cols=2)
    _t.style = "Table Grid"
    for i, h in enumerate(["Term", "Definition"]):
        c = _t.rows[0].cells[i]
        c.text = ""
        sh = OxmlElement("w:shd"); sh.set(qn("w:fill"), "E8EEF7")
        c._tc.get_or_add_tcPr().append(sh)
        r = c.paragraphs[0].add_run(h)
        r.bold, r.font.size, r.font.name = True, Pt(10.5), FONT
    for term, definition in _half:
        cells = _t.add_row().cells
        for i, v in enumerate((term, definition)):
            cells[i].text = ""
            p = cells[i].paragraphs[0]
            p.paragraph_format.line_spacing = LINE
            p.paragraph_format.space_after = Pt(2)
            r = p.add_run(v)
            r.font.size, r.font.name = Pt(10.5), FONT
        cells[0].width, cells[1].width = Inches(1.6), Inches(4.4)
    keep_on_one_page(_t)
    para("", after=10, spacing=LINE)

chapter("Appendix", numbered=False)
section("Appendix A — Application Screen")
if os.path.exists(SHOT):
    doc.add_picture(SHOT, width=Inches(USABLE_W))
    doc.paragraphs[-1].alignment = WD_ALIGN_PARAGRAPH.CENTER
    para("Figure A.1: Analyst dashboard showing risk metrics, decision mix, score "
         "distribution, accuracy results and flagged transactions", size=11, bold=True,
         align=WD_ALIGN_PARAGRAPH.CENTER, after=10, spacing=LINE)
section("Appendix B — Reproducing the Measured Results")
code_block("""# 1. Start the complete stack
docker compose up --build

# 2. Seed the synthetic datasets (run automatically by the API container)
python -m scripts.seed_mongo
python -m scripts.seed_neo4j

# 3. Replay the labelled dataset through the pipeline
python -m scripts.evaluate

# 4. Run the automated test suite (no databases required)
pytest -q""")


# ────────────────── back-fill lists of figures and tables ──────────────────
def fill_contents(anchor):
    """Write the table of contents with dot leaders and real page numbers."""
    anchor.alignment = WD_ALIGN_PARAGRAPH.CENTER
    anchor.paragraph_format.space_after = Pt(14)
    anchor.paragraph_format.line_spacing = LINE
    r = anchor.add_run("TABLE OF CONTENTS")
    r.bold, r.font.size, r.font.name = True, Pt(CHAP), FONT
    cursor = anchor
    entries = [(1, t) for t in FRONT_MATTER] + contents
    for level, title in entries:
        p = doc.add_paragraph()
        p.alignment = WD_ALIGN_PARAGRAPH.LEFT
        p.paragraph_format.line_spacing = LINE
        p.paragraph_format.space_after = Pt(4 if level == 1 else 2)
        p.paragraph_format.left_indent = Inches(0 if level == 1 else 0.3)
        p.paragraph_format.tab_stops.add_tab_stop(
            Inches(USABLE_W), WD_TAB_ALIGNMENT.RIGHT, WD_TAB_LEADER.DOTS)
        run = p.add_run(f"{title}\t{TOC_PAGES.get(title, '')}")
        run.bold = level == 1
        run.font.size, run.font.name = Pt(BODY), FONT
        cursor._p.addnext(p._p)
        cursor = p


def fill(anchor, heading_text, items):
    anchor.alignment = WD_ALIGN_PARAGRAPH.CENTER
    anchor.paragraph_format.space_after = Pt(12)
    anchor.paragraph_format.line_spacing = LINE
    r = anchor.add_run(heading_text)
    r.bold, r.font.size, r.font.name = True, Pt(CHAP), FONT
    cursor = anchor
    for label, title in items:
        p = doc.add_paragraph()
        p.paragraph_format.line_spacing = LINE
        p.paragraph_format.space_after = Pt(2)
        run = p.add_run(f"{label}:  {title}")
        run.font.size, run.font.name = Pt(BODY), FONT
        cursor._p.addnext(p._p)
        cursor = p


fill(LOT_ANCHOR, "LIST OF TABLES", tables)
fill(LOF_ANCHOR, "LIST OF FIGURES", figures)
fill_contents(TOC_ANCHOR)

# The PDF driver needs the heading list to look each page number up, and the
# table spans to check no table was split across a page break.
with open(os.path.join(HERE, "toc-entries.json"), "w") as f:
    json.dump(FRONT_MATTER + [t for _, t in contents], f, indent=2)
with open(os.path.join(HERE, "table-spans.json"), "w") as f:
    json.dump(table_spans, f, indent=2)

page_numbers()
refresh_fields_on_open()
doc.save(OUT)
print(f"Saved {OUT}")
print(f"  figures: {len(figures)}   tables: {len(tables)}   "
      f"contents entries: {len(FRONT_MATTER) + len(contents)}"
      f"{'' if TOC_PAGES else '   (page numbers not filled in yet)'}")
