"""
Build the Indus11 SRS document.

Structure and formatting follow the department template and the internal
guide's review comments:

  - 1.5 line spacing throughout — every paragraph, including table cells,
    captions and headings — and justified running text
  - 2.54 cm (1 in) margins on all four sides
  - no stray space before/after paragraphs
  - only chapters start on a new page; chapter titles centred at 16 pt,
    sub-topic titles at 14 pt
  - figures numbered per chapter (Figure 4.1, 5.3, ...), no repeated titles
  - every store is given its own data-dictionary table
  - Conclusion, References and Definitions appear last, unnumbered
  - References begin on their own page
  - the six UML/DFD figures (docs/diagrams/final-*.png) are supplied images —
    the dark-theme diagrams the user generated and asked to keep as-is, not
    PlantUML/Graphviz renders. They are not regenerated by this script; replace
    the PNG in place if a diagram needs to change. The .puml/.dot sources for
    the Times-New-Roman versions these replaced are left in the repo for
    reference but are no longer wired into the build.

    python docs/build_srs.py
"""
import docx_kit as kit
from docx_kit import *          # noqa: F401,F403 — the document-building vocabulary

OUT = os.path.expanduser("~/Downloads/Indus11_SRS.docx")
kit.use("toc-pages.json")

# ───────────────────────── FRONT MATTER ─────────────────────────
# The icon alone, not the wordmark: the registered title below is still Indus11.
doc.add_picture(os.path.join(HERE, "brand", "nirix-icon.png"), width=Inches(1.15))
doc.paragraphs[-1].alignment = WD_ALIGN_PARAGRAPH.CENTER
doc.paragraphs[-1].paragraph_format.space_after = Pt(14)
para("SOFTWARE REQUIREMENTS SPECIFICATION", CHAP, True, WD_ALIGN_PARAGRAPH.CENTER, 10)
para("INDUS11 — AI FINANCIAL RISK AND FRAUD DECISION ENGINE", CHAP, True,
     WD_ALIGN_PARAGRAPH.CENTER, 20)
para("A Software Group Project Report", BODY, False, WD_ALIGN_PARAGRAPH.CENTER, 4)
para("Semester 5   |   Academic Year 2026-27   |   Project ID: PRJ_CE_5_2026_7",
     BODY, False, WD_ALIGN_PARAGRAPH.CENTER, 20)
para("Submitted by", BODY, True, WD_ALIGN_PARAGRAPH.CENTER, 6)
for n, sid in [("Joshi Om", "24DCE052"), ("Krish Gajera", "24DCE040"),
               ("Drashti Dedaniya", "24DCE029")]:
    para(f"{n}   ({sid})", BODY, False, WD_ALIGN_PARAGRAPH.CENTER, 2)
para("", after=16)
para("Under the guidance of", BODY, False, WD_ALIGN_PARAGRAPH.CENTER, 4)
para("Dr. Deven Gol", BODY, True, WD_ALIGN_PARAGRAPH.CENTER, 2)
para("Assistant Professor, Department of Computer Engineering", BODY, False,
     WD_ALIGN_PARAGRAPH.CENTER, 20)
para("DEVANG PATEL INSTITUTE OF ADVANCE TECHNOLOGY AND RESEARCH (DEPSTAR)",
     BODY, True, WD_ALIGN_PARAGRAPH.CENTER, 3)
para("CHAROTAR UNIVERSITY OF SCIENCE AND TECHNOLOGY (CHARUSAT)", BODY, True,
     WD_ALIGN_PARAGRAPH.CENTER, 3)
para("Changa, Gujarat — 388421", BODY, False, WD_ALIGN_PARAGRAPH.CENTER)

new_page()
para("CERTIFICATE", CHAP, True, WD_ALIGN_PARAGRAPH.CENTER, 18)
para("This is to certify that the Software Requirements Specification entitled "
     "“Indus11 — AI Financial Risk and Fraud Decision Engine” is the bona fide work "
     "carried out by Joshi Om (24DCE052), Krish Gajera (24DCE040) and Drashti "
     "Dedaniya (24DCE029) of Semester 5, Department of Computer Engineering, DEPSTAR, "
     "CHARUSAT, in partial fulfilment of the requirements of the Software Group "
     "Project during the academic year 2026-27.", after=48)
_c = doc.add_table(rows=1, cols=2)
for i, txt in enumerate(["Dr. Deven Gol\nInternal Guide\nAssistant Professor\n"
                         "Computer Engineering",
                         "Head of Department\nComputer Engineering\n"
                         "DEPSTAR, CHARUSAT"]):
    cell = _c.cell(0, i)
    cell.text = ""
    p = cell.paragraphs[0]
    # Left-aligned: the body style is justified, which spreads each line of a
    # short multi-line signature block across the whole cell.
    p.alignment = WD_ALIGN_PARAGRAPH.LEFT
    p.paragraph_format.line_spacing = LINE
    p.paragraph_format.space_after = Pt(0)
    r = p.add_run(txt)
    r.font.size, r.font.name = Pt(BODY), FONT
    cell.width = Inches(3.0)
para("", after=10)
para("Date: ______________                    Place: Changa")

new_page()
para("ACKNOWLEDGEMENT", CHAP, True, WD_ALIGN_PARAGRAPH.CENTER, 18)
para("The satisfaction that accompanies the successful completion of any task would be "
     "incomplete without mentioning the people who made it possible, and whose constant "
     "guidance and encouragement crowned our effort with success.", after=10)
para("We are deeply indebted to our internal guide, Dr. Deven Gol, Assistant Professor, "
     "Department of Computer Engineering, DEPSTAR, for his valuable guidance, his "
     "patience with our drafts and the detailed review comments that shaped both this "
     "project and this document. His insistence on measured results rather than claims "
     "has improved our work considerably.", after=10)
para("We extend our sincere thanks to the Head of the Department of Computer "
     "Engineering and to the Principal of Devang Patel Institute of Advance Technology "
     "and Research (DEPSTAR) for providing us with the laboratory facilities, the "
     "academic environment and the freedom to pursue this problem.", after=10)
para("We are thankful to the faculty members of the Department of Computer Engineering "
     "for the foundation in databases, software engineering and machine learning on "
     "which this project rests, and to our classmates for their review and testing of "
     "our early prototypes.", after=10)
para("We also acknowledge the open-source communities behind FastAPI, MongoDB, Neo4j, "
     "Redis, ChromaDB, LangChain, Ollama and React, and the authors of the research "
     "cited in this report, whose work made a project of this scope possible within a "
     "single semester.", after=10)
para("Finally, we thank our parents and families for their constant support and "
     "encouragement throughout the course of this work.", after=24)
for n, sid in [("Joshi Om", "24DCE052"), ("Krish Gajera", "24DCE040"),
               ("Drashti Dedaniya", "24DCE029")]:
    para(f"{n} ({sid})", align=WD_ALIGN_PARAGRAPH.RIGHT, after=2)

new_page()
para("ABSTRACT", CHAP, True, WD_ALIGN_PARAGRAPH.CENTER, 18)
para("Indus11 is an AI-powered financial fraud detection and decision support system "
     "developed to identify suspicious banking transactions using a multi-layer risk "
     "assessment approach. The system addresses the limitations of conventional "
     "rule-based fraud detection by combining deterministic rules, graph-based "
     "relationship analysis, and Retrieval-Augmented Generation (RAG) to produce "
     "explainable risk decisions.")
para("The application is implemented using Python 3.12 and FastAPI for the backend "
     "APIs, React for the analyst dashboard, MongoDB (Beanie ODM) for transactional "
     "data storage, Neo4j for relationship analysis, Redis for caching, and ChromaDB "
     "as the vector database for document retrieval. LangChain and Ollama integrate "
     "the Large Language Model with the RAG pipeline, enabling the system to retrieve "
     "relevant banking policies, fraud guidelines, and historical cases before "
     "generating contextual explanations for analysts.")
para("Incoming transactions are evaluated through a three-layer scoring pipeline. The "
     "rule engine contributes 0–40 risk points based on predefined fraud indicators, "
     "graph analysis contributes 0–30 points by detecting shared devices, IP "
     "addresses, and circular transaction flows among accounts, while the RAG-based "
     "reasoning module contributes 0–30 points by validating contextual evidence. The "
     "combined score determines whether a transaction is classified as APPROVE, "
     "REVIEW, or BLOCK, while providing an explanation for every decision.")
para("The system was evaluated using a labelled fraud dataset and achieved 93.8% "
     "precision, 86.5% recall, and an F1-score of 0.90. Graph analysis successfully "
     "identified all 36 transactions belonging to the 3 planted mule rings, "
     "demonstrating the effectiveness of relationship-based fraud detection. During "
     "evaluation, no transaction reached the predefined BLOCK threshold because the "
     "seeded fraud accounts lacked stored historical profiles, preventing the "
     "amount-anomaly rule from contributing to their overall score. This identified a "
     "limitation in the current scoring mechanism rather than a characteristic of the "
     "dataset and highlights an area for future enhancement. Overall, the results "
     "demonstrate that integrating rule-based analysis, graph analytics, and "
     "RAG-based reasoning improves fraud detection while maintaining explainability "
     "and supporting financial investigators in making informed decisions.", after=10)
para("Keywords: fraud detection, explainable AI, graph analytics, retrieval-augmented "
     "generation, risk scoring", italic=True)

new_page()
TOC_ANCHOR = doc.add_paragraph()

new_page()
LOF_ANCHOR = doc.add_paragraph()
new_page()                      # the list of tables starts on its own page
LOT_ANCHOR = doc.add_paragraph()

# Front matter is not produced by chapter()/section(), so it is listed by hand.
FRONT_MATTER = ["CERTIFICATE", "ACKNOWLEDGEMENT", "ABSTRACT",
                "LIST OF FIGURES", "LIST OF TABLES"]

# ───────────────────────── CHAPTER 1 ─────────────────────────
start_body_numbering()
chapter("Introduction", new_page_first=False)
section("1.1 Purpose")
para("This document specifies the software requirements for Indus11, a real-time "
     "financial fraud detection and decision engine. It states what the system must "
     "do, the interfaces it exposes, the constraints it operates under and the quality "
     "attributes against which it is measured.")
para("The intended readers are the project team, the internal guide and the evaluation "
     "panel, and any developer who later integrates with or extends the system. Every "
     "measured figure quoted in this document comes from an executed benchmark run "
     "rather than an estimate. The arrangement of the sections follows the structure "
     "recommended for a software requirements specification in IEEE Std 830-1998 [1].")
section("1.2 Scope")
para("Indus11 accepts one financial transaction over a REST interface, analyses it "
     "with three independent detection engines and returns a composite risk score from "
     "0 to 100, a decision of APPROVE, REVIEW or BLOCK, and a plain-language "
     "explanation. A web dashboard allows an analyst to view live statistics, inspect "
     "any flagged transaction and override a review outcome.")
para("The following are outside the scope of the system: it does not move money or "
     "settle payments; it is not a core banking system; it processes synthetic data "
     "only; it performs no regulatory reporting; and the training of a supervised "
     "model is identified as future work.")
section("1.3 Document Overview")
para("Chapter 2 describes the system as a whole. Chapter 3 states the functional, "
     "non-functional and security requirements. Chapter 4 presents the system design: "
     "the architecture, the data flow at three levels, and the component and "
     "deployment views. Chapter 5 contains the use case, activity, sequence, class and "
     "state diagrams. Chapter 6 specifies the database design, from the entity "
     "relationship diagram to the data dictionary. The conclusion, the references and "
     "the definitions follow, and the appendices give the application screen, sample "
     "records from each data store and the commands that reproduce the measured results.")

# ───────────────────────── CHAPTER 2 ─────────────────────────
chapter("Overall Description")
section("2.1 Product Perspective")
para("Indus11 is a new, self-contained decision service rather than a replacement for "
     "an existing product. In a production setting it would sit beside a payment "
     "processor: the processor submits a transaction and acts on the returned "
     "decision. Commercial platforms occupy the same position in a payment flow — FICO "
     "Falcon Fraud Manager [6], the Feedzai RiskOps platform [7] and Featurespace ARIC "
     "Risk Hub [8] — and the distinguishing aim here is that the reasons for a decision "
     "are returned with it rather than held inside the model.")
para("The system comprises a FastAPI application [10], a React dashboard and four data "
     "stores, each with a distinct role — MongoDB for account profiles and the audit "
     "trail, reached through the Beanie object-document mapper [11]; Neo4j for the "
     "transaction graph; Redis for caching and the velocity window; and ChromaDB for "
     "the fraud-pattern knowledge base, retrieved through LangChain [12].")
section("2.2 Product Functions")
for fn in ["Accept and validate a transaction over a documented REST interface.",
           "Load account profiles from cache, falling back to the document store.",
           "Score the transaction against configurable rules, including a "
           "rolling-window velocity check.",
           "Detect fraud rings and shared-identity clusters in the transaction graph.",
           "Retrieve similar fraud patterns and generate a natural-language explanation.",
           "Combine the layer scores into one score and map it to a decision.",
           "Persist every analysis so that decisions can be audited.",
           "Present live statistics and flagged transactions on a dashboard.",
           "Allow an analyst to inspect a transaction and override a review decision.",
           "Measure detection accuracy against a labelled dataset.",
           "Protect the service with per-client rate limiting."]:
    bullet(fn)
section("2.3 User Characteristics")
table("User classes and their characteristics", ["User class", "Characteristics"],
      [["Fraud analyst", "Primary user. Reviews and acts on flagged transactions. "
                         "Understands fraud typologies but does not read code or write "
                         "queries, so each decision must be explained in plain language."],
       ["System administrator", "Deploys and operates the stack, tunes thresholds and "
                                "runs the seed and evaluation scripts."],
       ["Integrating developer", "Consumes the REST interface from a payment system. "
                                 "Requires accurate schemas and documented status codes."],
       ["Project evaluator", "Assesses the system against this specification and "
                             "reproduces the measured results."]],
      widths=[1.5, 4.5])
section("2.4 Operating Environment")
table("Operating environment", ["Element", "Requirement"],
      [["Hardware", "64-bit x86 or ARM machine, 8 GB RAM minimum, approximately 5 GB "
                    "free disk space. No graphics processor is required."],
       ["Operating system", "Linux, macOS or Windows with Docker support."],
       ["Runtime", "Python 3.12 for the backend, Node.js 20 for the dashboard build."],
       ["Databases", "MongoDB 7, Neo4j 5.20 Community Edition, Redis 7.2, ChromaDB."],
       ["Language model", "Ollama running llama3 locally, or the OpenAI service."],
       ["Client", "Any modern browser at 1280 pixels width or greater."]],
      widths=[1.4, 4.6])
section("2.5 Design Constraints")
for c in ["The system shall run in full on a single machine without a graphics processor.",
          "No real customer or payment data may be used; all datasets are synthetic.",
          "The language model shall contribute no more than 30 of the 100 points.",
          "The language model shall be able to run locally, at no external cost.",
          "The backend shall be written in Python 3.12 and the dashboard in React.",
          "Neo4j Community Edition is used, so enterprise-only features are unavailable.",
          "The sum of all layer score budgets shall equal 100.",
          "Credentials shall never be committed to version control."]:
    bullet(c)
section("2.6 Assumptions and Dependencies")
for a in ["The four data stores are reachable. If a store is unavailable the affected "
          "layer is recorded as failed rather than failing the request, and a "
          "transaction it would otherwise have approved is held for review.",
          "A local language model or an external service key is available. Without "
          "either, the rule and graph layers still produce a decision and only the "
          "written explanation is lost.",
          "The synthetic dataset is representative enough to compare configurations "
          "against one another, but not to predict production accuracy: fraud is far "
          "denser in it than in a real payment feed, so the measured precision is "
          "optimistic. Section 3.2 quantifies by how much.",
          "An account with no stored profile is treated as elevated risk rather than "
          "as safe.",
          "Decision thresholds are tunable for each deployment; the values quoted in "
          "this document are the defaults.",
          "Any change to a layer's score budget would require the thresholds and the "
          "accuracy baseline to be derived again."]:
    bullet(a)

# ───────────────────────── CHAPTER 3 ─────────────────────────
chapter("System Requirements")
section("3.1 Functional Requirements")
para("Each requirement is traceable to the module that implements it. The requirements "
     "are given in four tables — request handling and scoring; decision and "
     "persistence; accounts, graph, reporting and operations; then the dashboard, "
     "security and resilience — sized so that none has to run across a page break.")
table("Functional requirements — request handling and scoring",
      ["ID", "Requirement", "Module"],
      [["FR-1", "Accept a transaction over HTTP POST carrying identifier, sender, receiver, amount, currency and optional merchant, device, address and note fields.", "routes/transactions"],
       ["FR-2", "Validate every request against a schema and reject a malformed or non-positive amount before any analysis is performed.", "schemas/transaction"],
       ["FR-3", "Reject a duplicate transaction identifier with a conflict response so that a retried request does not produce a server error.", "routes/transactions"],
       ["FR-4", "Load sender and receiver profiles from cache, falling back to the document store, treating an unknown account as elevated risk.", "routes/transactions"],
       ["FR-5", "Score from 0 to 40 using blacklist, velocity, amount-anomaly, merchant and risk-tier rules and twenty-five banking anomaly rules, among them structuring and smurfing around the ₹10 lakh reporting threshold, dormant-account reactivation, new beneficiaries, devices and IP addresses on large payments, pass-through, fan-in and fan-out of funds, impossible travel, micro-test payments, split and round-amount payments, account draining, high-risk jurisdictions and scam phrases in the payment note, returning the reason for each rule that fired; return the maximum score immediately when either party is blacklisted.", "services/rule_engine"],
       ["FR-6", "Count transactions for an account within an exact ten-minute rolling window and flag more than five.", "core/redis_client"],
       ["FR-7", "Score from 0 to 30 by detecting shared devices, circular flows within four hops, fee-skimming chains and proximity to a known fraud cluster.", "services/graph_analyzer"],
       ["FR-8", "Record the transaction, its accounts, device and address in the graph so later transactions can be evaluated against it.", "services/graph_analyzer"],
       ["FR-9", "Retrieve similar fraud patterns and obtain a score from 0 to 30 with an explanation from the language model, marking the layer as failed when no language model is reachable or the assessment times out.", "services/rag_pipeline"]],
      widths=[0.5, 4.2, 1.3], size=9)
table("Functional requirements — decision and persistence",
      ["ID", "Requirement", "Module"],
      [["FR-10", "Execute the rule and graph layers concurrently and return the decision from those two; score the retrieval and language-model layer after the response and fold its result into the stored record.", "routes/transactions"],
       ["FR-11", "Compute the composite score as the sum of the layer scores, clamped to 100.", "services/decision_engine"],
       ["FR-12", "Map the composite score to APPROVE, REVIEW or BLOCK using configured thresholds.", "services/decision_engine"],
       ["FR-13", "Include the triggered signals in every response, and add the model's reasoning to the stored record when the language-model layer completes.", "services/decision_engine"],
       ["FR-14", "Persist every analysed transaction with its score, decision, explanation and note.", "models/transaction"],
       ["FR-15", "Return a previously analysed transaction by identifier, or a not-found response.", "routes/transactions"],
       ["FR-16", "List recent transactions, optionally filtered by decision.", "routes/transactions"],
       ["FR-17", "Allow an analyst to override a decision and reject any invalid value.", "routes/transactions"],
       ["FR-17a", "Mark a transaction whose language-model assessment is still outstanding, and clear the mark when it completes or fails.", "routes/transactions"]],
      widths=[0.5, 4.2, 1.3], size=9)
table("Functional requirements — accounts, graph, reporting and operations",
      ["ID", "Requirement", "Module"],
      [["FR-18", "Support creating and listing accounts and toggling blacklist status.", "routes/accounts"],
       ["FR-19", "Return the graph neighbourhood of an account to a depth of one to three hops.", "routes/graph"],
       ["FR-20", "Propagate fraud labels to accounts within two hops and assign a cluster identifier.", "services/graph_analyzer"],
       ["FR-21", "Report graph statistics for accounts, devices, addresses, transactions and labels.", "routes/graph"],
       ["FR-22", "Report dashboard statistics: decision counts and score histogram; aggregates over all transactions by day, merchant category, amount band and triggered flag; the most recent review/block transactions; and the latest accuracy results.", "routes/stats"],
       ["FR-23", "Replay a labelled dataset and report precision, recall, F1, a confusion matrix and ring detection.", "scripts/evaluate"],
       ["FR-24", "Derive decisions again across candidate thresholds and report no block threshold when none is reachable.", "scripts/evaluate"],
       ["FR-25", "Limit each client to 120 requests per minute overall and 30 on the analysis endpoint.", "core/rate_limit"],
       ["FR-26", "Expose a health endpoint reporting service status.", "routes/health"],
       ["FR-27", "Provide repeatable seed scripts for account profiles and a synthetic fraud graph.", "scripts/seed"]],
      widths=[0.5, 4.2, 1.3], size=9)
table("Functional requirements — dashboard, security and resilience",
      ["ID", "Requirement", "Module"],
      [["FR-28", "Display key figures, decisions by day, decision mix, graph entity counts, category and signal breakdowns, score distribution, flag rate by amount, accuracy, and the review queue with detail and override, in a light or dark theme.", "dashboard"],
       ["FR-29", "Require a shared key on the routes that override a decision, change blacklist status, propagate fraud labels, or report or restart a scoring component.", "core/security"],
       ["FR-30", "Restrict the graph layer's circular-flow detection to hops occurring within a configured window and in chronological order.", "services/graph_analyzer"],
       ["FR-31", "Withhold a written explanation that does not reference any triggered signal, and show the signal list alone in its place.", "services/decision_engine"],
       ["FR-32", "Show an outstanding language-model assessment on the dashboard and replace it with the final score when it arrives.", "dashboard"],
       ["FR-33", "Mark a scoring layer that cannot run as failed, name it in the explanation, record it with the transaction, and send a transaction that would otherwise be approved to review.", "services/decision_engine"],
       ["FR-34", "Report whether each scoring component's dependency is answering, and let an authorised user restart one component.", "routes/components"],
       ["FR-35", "Show a failed layer on the dashboard with its error and a control that restarts that component.", "dashboard"]],
      widths=[0.5, 4.2, 1.3], size=9)
section("3.2 Non-Functional Requirements")
para("Non-functional requirements are grouped below under performance, reliability, "
     "maintainability, testability, portability, usability and accuracy. Security "
     "requirements are stated separately in section 3.3.")
para("Performance. The values below were measured on the development machine, an "
     "Apple Silicon computer running without a graphics processor, and are reproduced by "
     "the commands in Appendix C.")
para("An earlier revision of this document reported a complete-pipeline latency of "
     "14,046 milliseconds, of which about 13.9 seconds was the language model. That "
     "measurement was taken when the language model was still inside the decision "
     "path. Following the first project review it was moved out of it, and the "
     "figures below are the current measurements.")
table("Measured performance", ["Measurement", "Value", "Note"],
      [["Rule engine", "8 ms", "Velocity check and in-memory rules."],
       ["Graph analyzer", "20 ms", "Graph write and four pattern queries, time-windowed."],
       ["Response, mean", "124 ms", "Rule and graph layers, measured over 29 requests."],
       ["Response, 95th percentile", "189 ms", "Slowest 1 request in 20."],
       ["Response, maximum", "287 ms", "Worst observed sample."],
       ["Within the 500 ms budget", "29 of 29", "Every sampled request."],
       ["Language model", "13-14 s", "Runs after the response, not inside it."]],
      widths=[1.9, 1.6, 2.5])
for n in ["The deterministic layers shall complete within 500 milliseconds per transaction.",
          "The rule and graph layers shall run concurrently, so that the response "
          "latency is bounded by the slower of the two rather than by their sum.",
          "The retrieval and language-model layer shall not delay the response. It is "
          "scored after the response has been returned, and its score and written "
          "explanation are added to the stored record when they are ready.",
          "A transaction whose language-model assessment is still outstanding shall be "
          "marked as such, so that a provisional decision is never mistaken for a "
          "final one.",
          "An identical transaction submitted twice shall receive an identical score. "
          "The language model is therefore configured at temperature zero; at the "
          "default setting the same transaction was measured scoring between 20 and "
          "26."]:
    bullet(n)
para("Reliability and maintainability.")
for n in ["The service shall hold no state between requests, so that an instance can be "
          "restarted without loss of data.",
          "An unavailable component shall never cause a transaction to be approved silently: "
          "a transaction scored while a layer could not run shall be held for review.",
          "The composite score shall be clamped so that no combination exceeds the range.",
          "Every decision shall be persisted with its explanation for audit."]:
    bullet(n)
para("Testability and portability.")
for n in ["The automated test suite shall run without any database or network access.",
          "The stack shall start with a single command on Linux, macOS or Windows."]:
    bullet(n)
table("Software quality attributes", ["Attribute", "How it is achieved"],
      [["Reliability", "A failed layer is recorded and holds the transaction for review; a duplicate "
                       "submission returns a defined conflict response."],
       ["Maintainability", "Each layer is a single function with one input and one "
                           "output type, so a layer can be replaced independently."],
       ["Testability", "One hundred and one automated tests run with no database or network."],
       ["Portability", "The entire stack is defined in one container composition file."],
       ["Usability", "Every decision is accompanied by a written explanation."],
       ["Accuracy", f"Precision {FLAGGED['precision']:.3f}, recall {FLAGGED['recall']:.3f}, "
                    f"F1 {FLAGGED['f1']:.3f} over {COUNTS['total']} transactions; "
                    f"{GRAPH['graph_flagged']} of {GRAPH['ring_transactions']} ring "
                    f"transactions flagged by the graph layer, {CYCLE_HITS} of them by "
                    "the circular-flow check."]],
      widths=[1.3, 4.7])
para("The precision figure above is measured on a dataset that is 25 per cent "
     "fraud, because a test set has to contain enough fraud to measure. A live "
     "payment feed carries closer to one fraudulent transaction in a thousand, "
     "and precision — unlike recall — depends on that ratio. Holding this run's "
     f"recall of {FLAGGED['recall']:.3f} and its false-positive rate of "
     f"{REALISTIC['false_positive_rate']:.4f} constant, the same detector on a "
     f"feed with {REALISTIC['prevalence']:.1%} fraud would show a precision of "
     f"{REALISTIC['precision']:.3f} — roughly eight false alarms for every fraud "
     "caught. That figure, not the headline one, is the number a deployment "
     "would have to staff against. It is reported here because the synthetic "
     "figure alone would materially overstate the system.")
section("3.3 Security Requirements")
for s in ["Credentials shall be supplied through environment variables and never committed.",
          "All input shall be validated against a strict schema before use.",
          "Database access shall use parameterised queries throughout.",
          "Rate limiting shall be applied for each client address.",
          "Stored explanations shall be truncated to a bounded length.",
          "Account identifiers are the only data shared between stores; no payment "
          "instrument data is persisted.",
          "The routes that alter a stored decision, change an account's blacklist "
          "status, rewrite the graph's fraud labels, or report or restart a scoring component shall require a shared key "
          "supplied in a request header, compared in constant time.",
          "Browser access shall be restricted to configured origins rather than "
          "permitted from any origin.",
          "Fields that are incorporated into a language-model prompt shall be "
          "constrained to a fixed vocabulary or a bounded length, so that submitted "
          "text cannot be used to redirect the model's assessment.",
          "Full user authentication and authorisation are not implemented in the "
          "current version. The shared-key check above covers the routes whose misuse "
          "would alter a decision; per-user authentication remains recorded as future "
          "work, and the interface is intended for a trusted network in the meantime."]:
    bullet(s)

# ───────────────────────── CHAPTER 4 ─────────────────────────
chapter("System Design")
section("4.1 Overall Architecture")
para("The system is organised as a five-layer pipeline. The first layer validates the "
     "request and loads context. The second and third layers, the rule engine and the "
     "graph analyzer, score the transaction concurrently, and the fifth layer "
     "aggregates their scores and determines the decision that is returned. The fourth "
     "layer, retrieval-augmented generation, is scored after the response has been "
     "sent and its result is folded into the stored record; it was moved out of the "
     "request path following the first project review, where its 13 to 14 second "
     "latency was identified as unacceptable inside a decision that a payment system "
     "must return in under a second.")
para("Two of the scoring layers are adapted from published work. The graph layer takes "
     "the network-based view of card-fraud detection set out by Van Vlasselaer and "
     "others [2] and the semi-supervised propagation of fraud labels across a "
     "transaction graph described by Lebichot and others [3]; the Cypher patterns "
     "themselves follow the fraud-detection recipes in the Neo4j developer "
     "documentation [9]. The fourth layer applies retrieval-augmented generation, in "
     "which documents retrieved from a knowledge base are supplied to a language model "
     "as context for its answer [5].")
figure("01-architecture.png", "System architecture — five-layer pipeline")
section("4.2 Context Diagram")
para("The context diagram shows the system as a single process together with the "
     "external entities that exchange data with it.")
figure("final-dfd0.png", "Data flow diagram — Level 0 (context diagram)")
section("4.3 Data Flow Diagram — Level 1")
para("The level 1 diagram decomposes the system into its seven principal processes and "
     "shows the data stores each process reads from and writes to.")
figure("final-dfd1.png", "Data flow diagram — Level 1")
section("4.4 Data Flow Diagram — Level 2")
para("The level 2 diagram decomposes process 3.0, the rule engine, into its individual "
     "checks. The blacklist check runs first and ends the evaluation at the maximum of "
     "40 points when either party is blacklisted. Otherwise the velocity check adds the "
     "transaction's timestamp to a ten-minute window held in Redis and counts the "
     "entries, and the amount, merchant and risk-tier checks follow. The checks read the "
     "profiles already loaded by process 2.0. The twenty-five banking anomaly checks then read "
     "the sender's payment history from Redis and record the new payment in the same "
     "round trip; with the velocity check they are the only checks that touch a data store.")
figure("12-dfd2.png", "Data flow diagram — Level 2, process 3.0")
section("4.5 Component Diagram")
para("The component diagram shows the parts of the FastAPI application and the stores "
     "and services each one depends on. The routers call the rule engine, the graph "
     "analyzer and the decision engine directly, and hand the language-model layer to a "
     "background task limited to four concurrent assessments with a 180-second timeout. "
     "The component routes report whether each layer's dependency is answering and restart "
     "one layer on request. The API-key guard applies to those routes and to the three "
     "that change stored data: the "
     "decision override, the blacklist toggle and fraud label propagation.")
figure("07-component.png", "Component diagram")
section("4.6 Deployment Diagram")
para("The deployment diagram follows docker-compose.yml: five containers on one host, "
     "with named volumes for MongoDB, Neo4j and Redis and a bind mount for the ChromaDB "
     "files. The API container waits until the three databases report healthy, seeds "
     "MongoDB and Neo4j, then starts. Ollama runs on the host outside Docker and is "
     "reached through host.docker.internal. On the development machine the same services "
     "run natively and are started by scripts/run_local.sh.")
figure("08-deployment.png", "Deployment diagram — Docker Compose")

# ───────────────────────── CHAPTER 5 ─────────────────────────
chapter("UML Diagrams")
section("5.1 Use Case Diagram")
para("The use case diagram identifies the three actors and the services each may invoke.")
figure("final-usecase.png", "Use case diagram")
section("5.2 Activity Diagram")
para("The activity diagram follows one transaction across the participants. The rule "
     "and graph layers score in parallel and set a provisional decision, the record is "
     "stored and the response returned, and the language-model layer then runs in the "
     "background. If it answers within the time limit its score and explanation are "
     "added and the decision is banded again; if not, the layer is recorded as failed and a "
     "transaction that would have been approved is held for review. "
     "An analyst can approve or block a transaction held for review.")
figure("03-activity.png", "Activity diagram — transaction analysis workflow")
section("5.3 Sequence Diagram")
para("The sequence diagram shows the calls behind one POST /api/v1/transactions/analyze "
     "request in the order they occur. The response is sent after the insert and before "
     "the language model is called, so the client receives rag_pending set to true and "
     "polls GET /api/v1/transactions/{tx_id} until the flag clears. A duplicate tx_id "
     "is rejected by the unique index with 409 Conflict, and no background task is "
     "started for it.")
figure("04-sequence.png", "Sequence diagram — transaction analysis")
section("5.4 Class Diagram")
para("The class diagram shows the domain classes, the abstract analysis layer with its "
     "three concrete implementations, and the relationships between them.")
figure("final-class.png", "Class diagram — core domain and service classes")
section("5.5 State Diagram")
para("The state diagram gives the lifecycle of a transaction record. A record is created "
     "only after scoring, so a request rejected at validation or as a duplicate never "
     "reaches the store. Every stored record passes through a provisional state while "
     "its language-model assessment is outstanding, and if that assessment fails or "
     "times out the layer is recorded as failed and the decision is banded again, with an "
     "approval raised to review. The dashboard offers the "
     "approve and block actions only on a transaction under review.")
figure("06-state.png", "State diagram — lifecycle of a transaction")

# ───────────────────────── CHAPTER 6 ─────────────────────────
chapter("Database Design")
section("6.1 Entity Relationship Diagram")
para("The entity relationship diagram spans two stores. Accounts and transactions are "
     "MongoDB collections; devices, IP addresses and the relationships between accounts "
     "are held in Neo4j, where the graph layer queries them. The keys marked as foreign "
     "keys are logical ones, enforced by the application, because neither store imposes "
     "referential constraints across collections or between stores.")
figure("09-er.png", "Entity relationship diagram", max_h=5.3)
section("6.2 Logical Data Schema")
para("The document store is schemaless, so the schema below is the logical one enforced "
     "by the application: the Beanie document models declare the fields, their types and "
     "their indexes, and those indexes are created when the application starts, so no "
     "migration step is required. The two collections and their keys are given first, "
     "followed by the field-level definition of each.")
table("Collections, keys and indexes",
      ["Collection", "Primary key", "Unique index", "Secondary indexes", "Referenced by"],
      [["accounts", "_id (ObjectId)", "account_id", "—",
        "transactions (sender and receiver); Neo4j Account"],
       ["transactions", "_id (ObjectId)", "tx_id",
        "sender_account_id, receiver_account_id, decision",
        "Neo4j Transaction"]],
      widths=[0.9, 1.0, 0.9, 1.5, 1.7], size=9.5)
table("Accounts collection", ["Field", "Type", "Constraint", "Description"],
      [["account_id", "String", "Unique index", "Primary business key."],
       ["owner_name", "String", "Required", "Account holder name (synthetic)."],
       ["country_code", "String", "Default", "Two-letter country code."],
       ["avg_monthly_transaction", "Float", "Default 0.0", "Baseline for the anomaly rule."],
       ["is_blacklisted", "Boolean", "Default false", "Forces the maximum rule score."],
       ["risk_tier", "String", "Default standard", "One of standard, elevated or high."]],
      widths=[1.6, 0.9, 1.2, 2.3], size=10)
table("Transactions collection", ["Field", "Type", "Constraint", "Description"],
      [["tx_id", "String", "Unique index", "A duplicate insert is rejected."],
       ["sender_account_id", "String", "Indexed", "Supports per-account history."],
       ["receiver_account_id", "String", "Indexed", "Counterparty account."],
       ["amount", "Float", "Greater than 0", "Transaction value."],
       ["currency", "String", "Default INR", "Currency code."],
       ["merchant_category", "String", "Optional", "Drives the merchant rule."],
       ["merchant_id", "String", "Optional", "Merchant identifier, when supplied."],
       ["device_id", "String", "Optional", "Identity signal for the graph layer."],
       ["ip_address", "String", "Optional", "Identity signal for the graph layer."],
       ["composite_score", "Integer", "0 to 100", "Final risk score."],
       ["decision", "String", "Indexed", "APPROVE, REVIEW or BLOCK."],
       ["explanation", "String", "Bounded length", "Signals and model reasoning."],
       ["note", "String", "Optional", "Free text supplied at submission."],
       ["rag_pending", "Boolean", "Default false", "True until the language-model layer updates the record."],
       ["created_at", "DateTime", "Default now", "Supports recent-first listing."]],
      widths=[1.6, 0.9, 1.2, 2.3], size=10)
section("6.3 Data Dictionary")
para("Every entity held outside the document store is defined below, one table per "
     "store. Together with the two collection tables above these cover all persisted "
     "data in the system.")
table("Graph node types (Neo4j)",
      ["Node label", "Properties", "Key", "Purpose"],
      [["Account", "account_id, risk_label, fraud_cluster", "account_id",
        "One vertex per party. risk_label carries fraud or fraud_adjacent and "
        "fraud_cluster names the seed account of the cluster."],
       ["Transaction", "tx_id, amount, timestamp", "tx_id",
        "One vertex per analysed transfer, retained as the graph-side record."],
       ["Device", "device_id", "device_id",
        "Shared-device identity signal, used to link otherwise unrelated accounts."],
       ["IPAddress", "address", "address",
        "Shared-address identity signal, used in the same way as Device."]],
      widths=[0.9, 1.7, 1.2, 2.2], size=9.5)
table("Graph relationship types (Neo4j)",
      ["Relationship", "From", "To", "Properties", "Purpose"],
      [["SENT", "Account", "Account", "tx_id, amount, timestamp",
        "One money movement. Circular-flow and fee-skimming patterns are found "
        "by traversing two to four of these within 72 hours."],
       ["USED_DEVICE", "Account", "Device", "—",
        "Supports shared-device cluster detection."],
       ["USED_IP", "Account", "IPAddress", "—",
        "Supports shared-address cluster detection."],
       ["CONNECTED_TO", "Account", "Account", "—",
        "Materialised from a shared device or address; traversed by fraud label "
        "propagation to a depth of two."]],
      widths=[1.1, 0.9, 0.9, 1.1, 2.0], size=9.5)
table("Cache keys (Redis)",
      ["Key pattern", "Type", "Value", "Lifetime"],
      [["account:<account_id>", "String (JSON)", "Serialised account profile", "300 seconds"],
       ["velocity:<account_id>", "Sorted set",
        "Transaction timestamps scored by epoch second", "600 second rolling window"],
       ["velocity:<account_id> member", "String",
        "Event timestamp with a random suffix, so simultaneous events are distinct",
        "Aged out with its window"],
       ["lastseen:<account_id>", "String", "Epoch second of the account's last payment",
        "400 days"],
       ["payees:<account_id>", "Sorted set", "Receivers paid, scored by last payment time",
        "400 days"],
       ["inbound:<account_id>", "Sorted set",
        "Amounts received and who sent them, scored by time", "2 days"],
       ["outbound:<account_id>", "Sorted set",
        "Amounts paid and to whom, scored by time", "2 days"],
       ["senders:<account_id>", "Sorted set", "Accounts that paid this one, by time", "2 days"],
       ["devices:<account_id>, ips:<account_id>", "Sorted set",
        "Devices and IP addresses used, by last use", "400 days"],
       ["lastloc:<account_id>", "String", "Latitude, longitude and time of the last located payment",
        "400 days"],
       ["categories:<account_id>", "Set", "Merchant categories the account has paid", "400 days"],
       ["merchant:<merchant_id>", "Sorted set", "Accounts paying the merchant in the last 10 minutes",
        "1 hour"]],
      widths=[1.6, 1.1, 2.3, 1.0], size=9.5)
table("Vector store (ChromaDB)",
      ["Collection", "Field", "Type", "Description"],
      [["fraud_patterns", "id", "String", "Stable identifier of the pattern document, p01 to p58."],
       ["fraud_patterns", "document", "Text",
        "Description of one fraud typology; 58 documents are upserted on startup."],
       ["fraud_patterns", "embedding", "Vector",
        "Embedding used for similarity retrieval by the RAG layer."],
       ["fraud_patterns", "metadata.type", "String",
        "Typology group, for example synthetic_identity, money_mule, "
        "account_takeover or wire_fraud."]],
      widths=[1.2, 1.4, 0.9, 2.5], size=9.5)
para("Transaction records are retained indefinitely to preserve the audit trail, and no "
     "deletion path is exposed through the interface. Referential integrity between "
     "accounts and transactions is enforced by the application, since the document "
     "store does not impose foreign keys. Both seed scripts are idempotent.")
para("Indefinite retention has a consequence for the graph that was found by "
     "measurement rather than by reasoning. The circular-flow query originally matched "
     "any path returning to the sender across the whole retained history: 1,486 stored "
     "transactions produced 51,146 such paths, because any ordinary account that both "
     "sends and receives money eventually forms one. Almost half of that pattern's "
     "detections were on legitimate traffic as a result. The query is therefore "
     "restricted to hops falling within a bounded window and occurring in "
     "chronological order, which is the shape of a laundering chain rather than of "
     "ordinary commerce. Bounding the query is a separate decision from bounding "
     "storage, and only the former has been taken; an archival policy for the graph "
     "itself remains outstanding.")

# ────────────────── UNNUMBERED CLOSING SECTIONS ──────────────────
chapter("Conclusion and Future Enhancements", numbered=False)
para("Indus11 shows that detection capability and explainability need not be traded "
     "against one another, which is the trade-off reported for explainable ensemble "
     "methods in financial fraud detection [4]. Combining deterministic rules, graph "
     "traversal and a retrieval-augmented language model produced "
     f"{FLAGGED['precision']*100:.1f} per cent precision at "
     f"{FLAGGED['recall']*100:.1f} per cent recall on a labelled synthetic dataset of "
     f"{COUNTS['total']} transactions, while every decision carries the list of signals "
     "that caused it.")
para("The graph layer justified its inclusion. It flagged "
     f"{GRAPH['graph_flagged']} of the {GRAPH['ring_transactions']} planted mule-ring "
     "transactions, which rules that examine a single transaction cannot detect by "
     f"construction. The circular-flow check itself fired on {CYCLE_HITS} of them; the "
     "rest were flagged because the receiving account lies within two hops of a known "
     "fraud account.")
para("That check has a limitation found while rehearsing the review demonstration. It "
     "follows a cycle outward from the sender and requires every hop to be later than "
     "the one before, but the transaction that closes a ring is always the newest hop, "
     "so the closing transfer never matches. A ring is recognised only when its "
     "originator sends again. Following the path back from the receiver to the sender "
     "instead would catch the ring on the transfer that completes it.")
para("The evaluation also produced a negative result worth recording. No transaction "
     "reached the configured block threshold, so nothing is blocked automatically and "
     "every detection reaches an analyst. Lowering the threshold would automate "
     "blocking at the cost of also blocking the false positives, which is a policy "
     "decision requiring evidence rather than a change of configuration.")
para("Planned enhancements, in order of priority:")
for e in ["Resolve the block-threshold trade-off using the recorded transaction scores.",
          "Detect a money-mule ring on the transfer that closes it, and re-run the "
          "evaluation to measure the change.",
          "Extend the present shared-key check on the decision-altering routes to "
          "per-user authentication, and add structured request logging.",
          "Build an interactive fraud-ring visualisation on the existing graph endpoint.",
          "Investigate the seven undetected frauds and add fan-in and fan-out graph patterns.",
          "Train a supervised classifier as a fourth scoring signal.",
          "Bound the growth of the transaction graph with a retention or archival "
          "policy, so that query cost does not grow with the whole retained history.",
          "Validate against a public labelled dataset to obtain a realistic precision figure."]:
    bullet(e)

chapter("References", numbered=False)
para("Sources are listed in IEEE style and are referred to in the text by their number "
     "in square brackets.", after=10)
for i, r in enumerate([
    "IEEE, “IEEE Recommended Practice for Software Requirements Specifications,” "
    "IEEE Std 830-1998, Institute of Electrical and Electronics Engineers, 1998.",
    "V. Van Vlasselaer, C. Bravo, O. Caelen, T. Eliassi-Rad, L. Akoglu, M. Snoeck and "
    "B. Baesens, “APATE: A novel approach for automated credit card transaction fraud "
    "detection using network-based extensions,” Decision Support Systems, vol. 75, "
    "pp. 38–48, 2015.",
    "B. Lebichot, F. Braun, O. Caelen and M. Saerens, “A graph-based, semi-supervised, "
    "credit card fraud detection system,” in Complex Networks and Their Applications V, "
    "Springer, 2017, pp. 721–733.",
    "D. Vijayanand and G. S. Smrithy, “Explainable AI-enhanced ensemble learning for "
    "financial fraud detection,” 2025, doi:10.1177/18724981241289751.",
    "P. Lewis, E. Perez, A. Piktus, F. Petroni, V. Karpukhin and others, "
    "“Retrieval-augmented generation for knowledge-intensive NLP tasks,” Advances in "
    "Neural Information Processing Systems, vol. 33, pp. 9459–9474, 2020.",
    "FICO, “Falcon Fraud Manager,” product documentation, 2026. [Online]. "
    "Available: https://www.fico.com",
    "Feedzai, “RiskOps platform,” product overview, 2026. [Online]. "
    "Available: https://feedzai.com",
    "Featurespace, “ARIC Risk Hub,” product overview, 2026. [Online]. "
    "Available: https://www.featurespace.com",
    "Neo4j, “Graph algorithms for fraud detection,” developer documentation, 2026. "
    "[Online]. Available: https://neo4j.com/developer",
    "S. Ramirez, “FastAPI documentation,” 2026. [Online]. "
    "Available: https://fastapi.tiangolo.com",
    "MongoDB Inc., “MongoDB manual and Beanie ODM documentation,” 2026. [Online]. "
    "Available: https://www.mongodb.com/docs",
    "LangChain and Chroma documentation, 2026. [Online]. "
    "Available: https://python.langchain.com",
], 1):
    p = doc.add_paragraph()
    p.alignment = WD_ALIGN_PARAGRAPH.JUSTIFY
    p.paragraph_format.left_indent = Inches(0.4)
    p.paragraph_format.first_line_indent = Inches(-0.4)
    p.paragraph_format.line_spacing = LINE
    p.paragraph_format.space_after = Pt(6)
    run = p.add_run(f"[{i}]  {r}")
    run.font.size, run.font.name = Pt(BODY), FONT

chapter("Definitions, Acronyms and Abbreviations", numbered=False)

_DEFINITIONS = [
    ("API", "Application Programming Interface."),
    ("APPROVE", "Decision for a composite score of 0 to 39; the transaction proceeds."),
    ("BLOCK", "Decision for a composite score of 70 or above; the transaction is refused."),
    ("Composite score", "The sum of the three layer scores, clamped to 100."),
    ("Confusion matrix", "A table cross-tabulating the decision taken against the true label."),
    ("DFD", "Data Flow Diagram."),
    ("ER", "Entity Relationship."),
    ("F1", "The harmonic mean of precision and recall."),
    ("Fee skimming", "Each hop of a mule chain passing on slightly less money than it received."),
    ("Flag", "A signal code together with the values that triggered it."),
    ("HTTP", "Hypertext Transfer Protocol."),
    ("JSON", "JavaScript Object Notation."),
    ("Layer", "One stage of the analysis pipeline that produces a score and flags."),
    ("LLM", "Large Language Model."),
    ("Money-mule ring", "Accounts cycling funds among themselves to disguise the origin."),
    ("ODM", "Object-Document Mapper."),
    ("Precision", "Of the transactions flagged, the proportion genuinely fraudulent."),
    ("RAG", "Retrieval-Augmented Generation."),
    ("Recall", "Of the genuinely fraudulent transactions, the proportion flagged."),
    ("REST", "Representational State Transfer."),
    ("REVIEW", "Decision for a composite score of 40 to 69; held for a human analyst."),
    ("SRS", "Software Requirements Specification."),
    ("TTL", "Time To Live; the expiry period of a cached entry."),
    ("UML", "Unified Modeling Language."),
    ("Velocity", "The number of transactions an account makes inside a rolling window."),
]
# Split so neither half runs across a page break at 1.5 line spacing — one
# 25-row table doesn't fit a single page under the wider margins.
_HALF = (len(_DEFINITIONS) + 1) // 2
for _half in (_DEFINITIONS[:_HALF], _DEFINITIONS[_HALF:]):
    _t = doc.add_table(rows=1, cols=2)
    _t.style = "Table Grid"
    for i, h in enumerate(["Term", "Definition"]):
        c = _t.rows[0].cells[i]
        c.text = ""
        sh = OxmlElement("w:shd"); sh.set(qn("w:fill"), "E8EEF7")
        c._tc.get_or_add_tcPr().append(sh)
        r = c.paragraphs[0].add_run(h)
        r.bold, r.font.size, r.font.name = True, Pt(10.5), FONT
    for term, definition in _half:
        cells = _t.add_row().cells
        for i, v in enumerate((term, definition)):
            cells[i].text = ""
            p = cells[i].paragraphs[0]
            p.paragraph_format.line_spacing = LINE
            p.paragraph_format.space_after = Pt(2)
            r = p.add_run(v)
            r.font.size, r.font.name = Pt(10.5), FONT
        cells[0].width, cells[1].width = Inches(1.6), Inches(4.4)
    keep_on_one_page(_t)
    para("", after=10, spacing=LINE)

chapter("Appendix", numbered=False)
section("Appendix A — Application Screen")
if os.path.exists(SHOT):
    doc.add_picture(SHOT, width=Inches(USABLE_W))
    doc.paragraphs[-1].alignment = WD_ALIGN_PARAGRAPH.CENTER
    para("Figure A.1: Analyst dashboard showing the key figures, decisions by day, decision "
         "mix, graph entity counts and the category and signal breakdowns, captured from the "
         "running system on 14 September 2026", size=11, bold=True,
         align=WD_ALIGN_PARAGRAPH.CENTER, after=10, spacing=LINE)
section("Appendix B — Sample Database Records")
para("The records below were read from the running system on 11 September 2026, one "
     "from each store. MongoDB object identifiers are omitted, and the transaction's "
     "explanation is shortened where marked.")
para("MongoDB — accounts collection", bold=True, align=WD_ALIGN_PARAGRAPH.LEFT,
     after=4).paragraph_format.keep_with_next = True
code_block("""{
  "account_id": "ACC-014",
  "owner_name": "Nadia Osei",
  "avg_monthly_transaction": 88000.0,
  "is_blacklisted": true,
  "country_code": "CA",
  "risk_tier": "high"
}""")
para("MongoDB — transactions collection", bold=True, align=WD_ALIGN_PARAGRAPH.LEFT,
     after=4).paragraph_format.keep_with_next = True
code_block("""{
  "tx_id": "REHEARSE-1789102514-2",
  "sender_account_id": "ACC-013",
  "receiver_account_id": "ACC-451",
  "amount": 704000.0,
  "currency": "INR",
  "merchant_category": "wire_transfer",
  "merchant_id": null,
  "device_id": "DEV-FRAUD-A",
  "ip_address": "203.0.113.66",
  "composite_score": 83,
  "decision": "BLOCK",
  "explanation": "Triggered signals: AMOUNT_ANOMALY (₹704000 vs avg
      ₹52000); HIGH_RISK_MERCHANT (wire_transfer); HIGH_RISK_SENDER_TIER;
      SHARED_DEVICE (8 accounts on device DEV-FRAUD-A); SHARED_IP (12
      accounts on IP 203.0.113.66); FRAUD_CLUSTER_PROXIMITY (5 fraud
      neighbors); wire_fraud. A massive wire transfer from a high-risk
      sender account, with a confirmed amount anomaly, [...]",
  "note": null,
  "rag_pending": false,
  "created_at": "2026-09-11T04:55:16.568000"
}""")
para("Neo4j — node and relationships", bold=True, align=WD_ALIGN_PARAGRAPH.LEFT,
     after=4).paragraph_format.keep_with_next = True
code_block("""(:Account {account_id: "ACC-451", risk_label: "fraud"})
  -[:SENT {tx_id: "STX-00001", amount: 7197.13,
           timestamp: "2026-06-01T00:00:00"}]->
(:Account {account_id: "ACC-452"})

(:Account {account_id: "ACC-451"})
  -[:USED_DEVICE]->
(:Device {device_id: "DEV-FRAUD-A"})""")
para("Redis — velocity window", bold=True, align=WD_ALIGN_PARAGRAPH.LEFT,
     after=4).paragraph_format.keep_with_next = True
code_block("""key     velocity:ACC-953          (sorted set, 600 second window)
member  "1789103111.565832:1e9ec825"
score   1789103111.565832""")
para("ChromaDB — fraud_patterns collection", bold=True, align=WD_ALIGN_PARAGRAPH.LEFT,
     after=4).paragraph_format.keep_with_next = True
code_block("""id        p05
metadata  {"type": "money_mule"}
document  Mule fee skimming: funds pass through a chain of accounts with
          each hop forwarding 85-95% of the amount received, the remainder
          kept as the mule's cut. Amounts that shrink hop-by-hop are the
          signature.""")
section("Appendix C — Reproducing the Measured Results")
code_block("""# 1. Start the stack in containers; the API container seeds both databases
docker compose up --build

#    or run it natively on the development machine, with a fresh seed
./scripts/run_local.sh --seed

# 2. Replay the labelled dataset (over an hour with the language model)
python -m scripts.evaluate

# 3. Measure response latency on the decision path
python -m scripts.benchmark_latency

# 4. Run the automated test suite (no databases required)
pytest -q""")


# ────────────────── back-fill lists of figures and tables ──────────────────
fill(LOT_ANCHOR, "LIST OF TABLES", tables)
fill(LOF_ANCHOR, "LIST OF FIGURES", figures)
fill_contents(TOC_ANCHOR, FRONT_MATTER)

# The PDF driver needs the heading list to look each page number up, and the
# table spans to check no table was split across a page break.
with open(os.path.join(HERE, "toc-entries.json"), "w") as f:
    json.dump(FRONT_MATTER + [t for _, t in contents], f, indent=2)
with open(os.path.join(HERE, "table-spans.json"), "w") as f:
    json.dump(table_spans, f, indent=2)

page_numbers()
refresh_fields_on_open()
doc.save(OUT)
print(f"Saved {OUT}")
print(f"  figures: {len(figures)}   tables: {len(tables)}   "
      f"contents entries: {len(FRONT_MATTER) + len(contents)}"
      f"{'' if TOC_PAGES else '   (page numbers not filled in yet)'}")
