"""
Build the weekly reports for one week, one file per team member.

The previous week's report is used as the template so the university's layout,
fonts and signature block carry over untouched; only the dates, the two bullet
lists and the references are rewritten.

References are held per member per week and checked against every earlier week
before a file is written. The guide's review found the same three sources
repeated in Weeks 1 and 2 and again in Weeks 3 and 4, so a repeat is an error
here rather than something to be noticed after submission.

    python docs/build_weekly.py
"""
import copy
import os
import re
import subprocess

from docx import Document
from docx.oxml.ns import qn
from docx.shared import Inches
from docx.text.paragraph import Paragraph

DOWNLOADS = os.path.expanduser("~/Downloads")
SOFFICE = "/Applications/LibreOffice.app/Contents/MacOS/soffice"

WEEK = 5
FROM_DATE, TO_DATE = "04-08-2026", "10-08-2026"
NEXT_FROM, NEXT_TO = "11-08-2026", "17-08-2026"

REPORTS = {
    "24DCE052": {
        "work": [
            "Drafted Chapters 1 to 3 of the Software Requirements Specification: purpose "
            "and scope, product perspective, user classes, operating environment, design "
            "constraints and assumptions.",
            "Wrote the functional requirements as a traceable table of 32 requirements, "
            "each naming the module that implements it, together with the non-functional "
            "requirements and the measured latency figures (rule engine 8 ms, graph "
            "analyzer 48 ms warm, complete pipeline 14.0 s).",
            "Wrote the database design chapter: collection keys and indexes, field-level "
            "definitions, and a separate data-dictionary table for the graph store, the "
            "cache and the vector store.",
            "Checked every schema table against the running code and corrected four "
            "errors, including a graph node label that did not match the Cypher, an index "
            "claimed on a field that is not indexed, and a cache key for rate limiting "
            "that the application never creates.",
            "Produced the deployment topology and its configuration table of containers, "
            "ports and volumes directly from the Docker Compose file.",
            "Automated the document build so the report, its contents page and its PDF are "
            "regenerated by a single command, and committed it to the shared repository.",
        ],
        "plans": [
            "Add API key authentication and structured request logging to the gateway.",
            "Profile the analyze endpoint and reduce the latency contributed by the "
            "language model.",
            "Re-run the evaluation after the block-threshold decision and update the "
            "measured figures in the specification.",
            "Prepare the platform walkthrough for the mid-semester demonstration.",
        ],
        "references": [
            "IEEE, “IEEE Recommended Practice for Software Requirements Specifications,” "
            "IEEE Std 830-1998, 1998.",
            "ISO/IEC/IEEE 29148:2018, “Systems and software engineering — Life cycle "
            "processes — Requirements engineering,” 2018.",
            "OpenAPI Initiative, “OpenAPI Specification, Version 3.1.0,” 2021. "
            "[Online]. Available: spec.openapis.org",
            "Compose Specification, “Docker Compose file reference,” 2026. "
            "[Online]. Available: compose-spec.io",
        ],
    },
    "24DCE040": {
        "work": [
            "Redrew the data flow diagrams in standard Gane–Sarson notation: the context "
            "diagram, a level 1 diagram with seven processes and five data stores, and a "
            "level 2 diagram expanding rule evaluation.",
            "Produced the complete UML set for the specification — use case, activity, "
            "sequence, class, state, component and deployment diagrams — together with the "
            "entity relationship diagram.",
            "Measured how small each diagram's text becomes once scaled to the page and "
            "found the class diagram reduced to roughly 5 pt, so the class and activity "
            "diagrams were each split in two and the deployment and level 1 diagrams "
            "reshaped; no diagram now falls below about 8 pt in print.",
            "Set every diagram in the report's own typeface and removed the titles baked "
            "into the images, since each figure now carries a numbered caption.",
            "Wrote the graph-layer section of the specification, describing the "
            "shared-device, circular-flow, fee-skimming and cluster-proximity checks and "
            "the Cypher patterns behind them.",
            "Committed the diagram sources rather than only the images, so any diagram can "
            "be regenerated instead of redrawn by hand.",
        ],
        "plans": [
            "Complete the interactive fraud-ring view in the dashboard on top of the "
            "neighbourhood endpoint.",
            "Add fan-in and fan-out mule patterns and measure the effect on ring recall.",
            "Benchmark the Cypher queries against the fully seeded graph.",
            "Investigate the seven frauds the current pipeline does not catch.",
        ],
        "references": [
            "Object Management Group, “Unified Modeling Language (UML), Version 2.5.1,” "
            "OMG, 2017.",
            "C. Gane and T. Sarson, Structured Systems Analysis: Tools and Techniques. "
            "Englewood Cliffs, NJ: Prentice-Hall, 1979.",
            "PlantUML, “Language Reference Guide,” 2026. [Online]. "
            "Available: plantuml.com",
            "Graphviz, “Drawing graphs with dot,” 2026. [Online]. Available: graphviz.org",
        ],
    },
    "24DCE029": {
        "work": [
            "Updated the Review-2 presentation with the measured accuracy results and "
            "rewrote the slides the internal guide had commented on.",
            "Wrote the presentation speaking script as a separate document, so that the "
            "slides carry the figures and the script carries the delivery.",
            "Made the flagged-transactions table interactive: filter chips showing live "
            "counts, a search across transaction and account identifiers, sortable score "
            "and time columns, and a proportional bar beside each score.",
            "Added motion to the dashboard — panels entering in sequence and key figures "
            "counting up — and made all of it switch off automatically for a viewer who "
            "has reduced motion enabled in their system settings.",
            "Built a static demo mode so the dashboard can be published and viewed without "
            "the backend running, and verified it by stopping the API entirely and serving "
            "the build, with every panel rendering and no console errors.",
            "Wrote the artificial-intelligence and dashboard sections of the "
            "specification, covering the retrieval pipeline, the explanation format and "
            "the analyst screens.",
        ],
        "plans": [
            "Add a decision-history timeline to the transaction detail view.",
            "Expand the fraud knowledge base with the patterns confirmed by the "
            "evaluation results.",
            "Run an accessibility pass over the dashboard against the contrast and "
            "keyboard requirements.",
            "Rehearse the mid-semester demonstration with the team.",
        ],
        "references": [
            "J. Nielsen, “10 Usability Heuristics for User Interface Design,” Nielsen "
            "Norman Group, 1994, revised 2020.",
            "W3C, “Web Content Accessibility Guidelines (WCAG) 2.2,” W3C Recommendation, "
            "2023. [Online]. Available: w3.org/TR/WCAG22",
            "Mozilla, “prefers-reduced-motion,” MDN Web Docs, 2026. [Online]. "
            "Available: developer.mozilla.org",
            "Recharts, “API reference,” 2026. [Online]. Available: recharts.org",
        ],
    },
}


def _set_text(paragraph, text):
    """Replace a paragraph's text, keeping the first run's formatting."""
    for run in paragraph.runs[1:]:
        run._r.getparent().remove(run._r)
    if paragraph.runs:
        paragraph.runs[0].text = text
    else:
        paragraph.add_run(text)


def _rewrite(paragraphs, lines):
    """Replace a run of paragraphs with `lines`, cloning the first for format."""
    first = paragraphs[0]
    for extra in paragraphs[1:]:
        extra._p.getparent().remove(extra._p)
    _set_text(first, lines[0])
    cursor = first._p
    for line in lines[1:]:
        clone = copy.deepcopy(first._p)
        cursor.addnext(clone)
        cursor = clone
        _set_text(Paragraph(clone, first._parent), line)


def _reference_paragraphs(doc):
    """The numbered paragraphs that follow the References heading."""
    out, seen_heading = [], False
    for p in doc.paragraphs:
        if p.text.strip().startswith("References"):
            seen_heading = True
            continue
        if seen_heading:
            if re.match(r"^\d+\.", p.text.strip()):
                out.append(p)
            elif out:
                break
    return out


def _key(reference):
    """Compare references loosely: lower case, letters and digits only."""
    return re.sub(r"[^a-z0-9]+", "", reference.lower())[:60]


def earlier_references(student_id):
    """Every reference this student has already cited, keyed to its week."""
    seen = {}
    for week in range(1, WEEK):
        docx = os.path.join(DOWNLOADS, f"{student_id}_Week{week}.docx")
        pdf = os.path.join(DOWNLOADS, f"{student_id}_Week{week}.pdf")
        if os.path.exists(docx):
            lines = [re.sub(r"^\s*\d+\.\s*", "", p.text)
                     for p in _reference_paragraphs(Document(docx))]
        elif os.path.exists(pdf):
            text = subprocess.run(["pdftotext", "-layout", pdf, "-"],
                                  check=True, capture_output=True, text=True).stdout
            lines = [re.sub(r"^\s*\d+\.\s*", "", ln)
                     for ln in text.splitlines() if re.match(r"^\s*\d+\.\s", ln)]
        else:
            continue
        for line in lines:
            seen.setdefault(_key(line), week)
    return seen


def build(student_id, spec):
    source = os.path.join(DOWNLOADS, f"{student_id}_Week{WEEK - 1}.docx")
    doc = Document(source)

    dates = doc.tables[1]
    # The template's first column is a shade too narrow for the project ID, so
    # "PRJ_CE_5_2026_7" wraps onto a second line in some renderers. Widen it.
    for column, width in zip(dates._tbl.tblGrid.findall(qn("w:gridCol")), (3.2, 2.8)):
        column.set(qn("w:w"), str(int(width * 1440)))
    for row in dates.rows:
        row.cells[0].width = Inches(3.2)
        row.cells[1].width = Inches(2.8)
    _set_text(dates.cell(1, 0).paragraphs[0], f"From Date: {FROM_DATE}")
    _set_text(dates.cell(1, 1).paragraphs[0], f"To Date: {TO_DATE}")

    for p in doc.paragraphs:
        if p.text.startswith("Work done from Date:"):
            _set_text(p, f"Work done from Date: {FROM_DATE} to {TO_DATE}")
        elif p.text.startswith("Plans for next week:"):
            _set_text(p, f"Plans for next week: Date: {NEXT_FROM} to {NEXT_TO}")

    _rewrite(doc.tables[2].cell(0, 0).paragraphs,
             [f"•  {line}" for line in spec["work"]])
    _rewrite(doc.tables[3].cell(0, 0).paragraphs,
             [f"•  {line}" for line in spec["plans"]])
    _rewrite(_reference_paragraphs(doc),
             [f"{i}.  {r}" for i, r in enumerate(spec["references"], 1)])

    out = os.path.join(DOWNLOADS, f"{student_id}_Week{WEEK}.docx")
    doc.save(out)
    return out


if __name__ == "__main__":
    for student_id, spec in REPORTS.items():
        already = earlier_references(student_id)
        repeats = [r for r in spec["references"] if _key(r) in already]
        if repeats:
            raise SystemExit(f"{student_id}: already cited in an earlier week — {repeats}")
        out = build(student_id, spec)
        subprocess.run([SOFFICE, "--headless", "--convert-to", "pdf",
                        "--outdir", DOWNLOADS, out], check=True, capture_output=True)
        print(f"{student_id}: {os.path.basename(out)} + .pdf — "
              f"{len(spec['references'])} references, none of the "
              f"{len(already)} cited in Weeks 1-{WEEK - 1}")
